/*
Purpose: Generate a single HTML health-check report for PostgreSQL after Oracle migration.
Area: Migration Validation
Usage:
  psql "host=<host> port=<port> dbname=<db> user=<user>" \
    -v report_file='postgres_360_migration_health_report.html' \
    -f 27_migration_validation/01_oracle_to_postgres_360_health_report.sql

Notes:
  - Runs read-only checks across objects, security, workload, vacuum, replication, and configuration.
  - Produces a simple PASS/WARN/FAIL report with suggested actions.
*/

\set ON_ERROR_STOP on
\pset pager off
\pset footer on
\pset border 1
\pset format html

\if :{?report_file}
\else
\set report_file 'postgres_360_migration_health_report.html'
\endif

\o :report_file

\qecho <!DOCTYPE html>
\qecho <html>
\qecho <head>
\qecho <meta charset="utf-8">
\qecho <title>PostgreSQL 360 Migration Health Report</title>
\qecho </head>
\qecho <body>
\qecho <h1>PostgreSQL 360 Migration Health Report</h1>
\qecho <p>This report is generated by SQL and highlights migration and operational risks with approximate fixes.</p>

\pset title 'Report Metadata'
SELECT
    current_database() AS database_name,
    current_user AS executed_by,
    version() AS postgres_version,
    pg_postmaster_start_time() AS instance_start_time,
    now() AS report_generated_at;

\set QUIET 1

CREATE TEMP TABLE tmp_pg360_check_results (
    check_id text NOT NULL,
    area text NOT NULL,
    severity_if_failing text NOT NULL,
    status text NOT NULL,
    issue_count bigint NOT NULL,
    threshold_rule text NOT NULL,
    evidence text NOT NULL,
    recommended_fix text NOT NULL
);

INSERT INTO tmp_pg360_check_results (
    check_id,
    area,
    severity_if_failing,
    status,
    issue_count,
    threshold_rule,
    evidence,
    recommended_fix
)
SELECT
    'ENV-001',
    'Environment',
    'MEDIUM',
    CASE WHEN e.installed THEN 'PASS' ELSE 'WARN' END,
    CASE WHEN e.installed THEN 0 ELSE 1 END,
    'pg_stat_statements extension should be installed for SQL visibility',
    CASE
        WHEN e.installed THEN 'pg_stat_statements is installed'
        ELSE 'pg_stat_statements extension is missing'
    END,
    'Install extension and preload library: CREATE EXTENSION pg_stat_statements; configure shared_preload_libraries.'
FROM (
    SELECT EXISTS (
        SELECT 1
        FROM pg_extension
        WHERE extname = 'pg_stat_statements'
    ) AS installed
) AS e

UNION ALL

SELECT
    'CFG-001',
    'Configuration',
    'CRITICAL',
    CASE WHEN c.enabled THEN 'PASS' ELSE 'FAIL' END,
    CASE WHEN c.enabled THEN 0 ELSE 1 END,
    'autovacuum must be enabled',
    'autovacuum=' || c.setting,
    'Enable autovacuum in postgresql.conf and restart/reload as required.'
FROM (
    SELECT
        setting,
        lower(setting) IN ('on', 'true', '1') AS enabled
    FROM pg_settings
    WHERE name = 'autovacuum'
) AS c

UNION ALL

SELECT
    'CFG-002',
    'Configuration',
    'MEDIUM',
    CASE WHEN c.enabled THEN 'PASS' ELSE 'WARN' END,
    CASE WHEN c.enabled THEN 0 ELSE 1 END,
    'track_io_timing should be enabled for accurate I/O diagnostics',
    'track_io_timing=' || c.setting,
    'Set track_io_timing=on and reload config to improve I/O root-cause analysis.'
FROM (
    SELECT
        setting,
        lower(setting) IN ('on', 'true', '1') AS enabled
    FROM pg_settings
    WHERE name = 'track_io_timing'
) AS c

UNION ALL

SELECT
    'SEC-001',
    'Security',
    'HIGH',
    CASE WHEN lower(s.setting) = 'scram-sha-256' THEN 'PASS' ELSE 'WARN' END,
    CASE WHEN lower(s.setting) = 'scram-sha-256' THEN 0 ELSE 1 END,
    'password_encryption should be scram-sha-256',
    'password_encryption=' || s.setting,
    'Set password_encryption=scram-sha-256 and rotate role passwords in phases.'
FROM (
    SELECT setting
    FROM pg_settings
    WHERE name = 'password_encryption'
) AS s

UNION ALL

SELECT
    'SEC-002',
    'Security',
    'MEDIUM',
    CASE WHEN s.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    s.issue_count,
    'Login superusers should be minimal (recommended <= 2)',
    CASE
        WHEN s.issue_count = 0 THEN 'login superusers=' || s.login_superusers || ' (within limit)'
        ELSE 'login superusers=' || s.login_superusers || '; sample=' || s.sample_roles
    END,
    'Reduce superuser usage; use least-privilege admin roles and controlled escalation.'
FROM (
    WITH super_roles AS (
        SELECT rolname
        FROM pg_roles
        WHERE rolsuper
          AND rolcanlogin
    )
    SELECT
        stats.login_superusers,
        GREATEST(stats.login_superusers - 2, 0)::bigint AS issue_count,
        stats.sample_roles
    FROM (
        SELECT
            count(*)::bigint AS login_superusers,
            COALESCE(
                (
                    SELECT string_agg(rolname, ', ')
                    FROM (
                        SELECT rolname
                        FROM super_roles
                        ORDER BY rolname
                        LIMIT 5
                    ) AS t
                ),
                'none'
            ) AS sample_roles
        FROM super_roles
    ) AS stats
) AS s

UNION ALL

SELECT
    'OBJ-001',
    'Objects',
    'CRITICAL',
    CASE WHEN i.issue_count = 0 THEN 'PASS' ELSE 'FAIL' END,
    i.issue_count,
    'No invalid/not-ready indexes expected',
    CASE
        WHEN i.issue_count = 0 THEN 'No invalid indexes'
        ELSE 'sample=' || i.sample_indexes
    END,
    'Rebuild affected indexes (for example REINDEX INDEX CONCURRENTLY schema.index_name).'
FROM (
    WITH idx AS (
        SELECT format('%I.%I', n.nspname, c.relname) AS index_name
        FROM pg_index x
        JOIN pg_class c
            ON c.oid = x.indexrelid
        JOIN pg_namespace n
            ON n.oid = c.relnamespace
        WHERE n.nspname !~ '^pg_'
          AND n.nspname <> 'information_schema'
          AND (NOT x.indisvalid OR NOT x.indisready)
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(index_name, ', ')
                FROM (
                    SELECT index_name
                    FROM idx
                    ORDER BY index_name
                    LIMIT 5
                ) AS s
            ),
            'none'
        ) AS sample_indexes
    FROM idx
) AS i

UNION ALL

SELECT
    'OBJ-002',
    'Schema Design',
    'HIGH',
    CASE WHEN t.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    t.issue_count,
    'Application tables should have primary keys',
    CASE
        WHEN t.issue_count = 0 THEN 'All user tables have primary keys'
        ELSE 'sample=' || t.sample_tables
    END,
    'Add primary keys for tables without PKs after confirming business keys and write patterns.'
FROM (
    WITH no_pk AS (
        SELECT format('%I.%I', n.nspname, c.relname) AS table_name
        FROM pg_class c
        JOIN pg_namespace n
            ON n.oid = c.relnamespace
        WHERE c.relkind = 'r'
          AND n.nspname !~ '^pg_'
          AND n.nspname <> 'information_schema'
          AND NOT EXISTS (
              SELECT 1
              FROM pg_constraint p
              WHERE p.conrelid = c.oid
                AND p.contype = 'p'
          )
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(table_name, ', ')
                FROM (
                    SELECT table_name
                    FROM no_pk
                    ORDER BY table_name
                    LIMIT 5
                ) AS s
            ),
            'none'
        ) AS sample_tables
    FROM no_pk
) AS t

UNION ALL

SELECT
    'OBJ-003',
    'Schema Design',
    'HIGH',
    CASE WHEN f.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    f.issue_count,
    'Foreign keys should have supporting indexes on referencing columns',
    CASE
        WHEN f.issue_count = 0 THEN 'All FKs have supporting indexes'
        ELSE 'sample=' || f.sample_fk
    END,
    'Create indexes on FK referencing columns to avoid parent UPDATE/DELETE slowdowns.'
FROM (
    WITH fk AS (
        SELECT
            c.oid AS constraint_oid,
            c.conname,
            c.conrelid,
            c.conkey,
            n.nspname AS schema_name,
            t.relname AS table_name
        FROM pg_constraint c
        JOIN pg_class t
            ON t.oid = c.conrelid
        JOIN pg_namespace n
            ON n.oid = t.relnamespace
        WHERE c.contype = 'f'
          AND n.nspname !~ '^pg_'
          AND n.nspname <> 'information_schema'
    ),
    missing AS (
        SELECT
            fk.schema_name,
            fk.table_name,
            fk.conname
        FROM fk
        WHERE NOT EXISTS (
            SELECT 1
            FROM pg_index i
            WHERE i.indrelid = fk.conrelid
              AND i.indisvalid
              AND i.indisready
              AND (
                  SELECT array_agg(k.attnum ORDER BY k.ord)
                  FROM unnest(i.indkey::smallint[]) WITH ORDINALITY AS k(attnum, ord)
                  WHERE k.ord <= array_length(fk.conkey, 1)
              ) = fk.conkey
        )
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('%I.%I(%I)', schema_name, table_name, conname), ', ')
                FROM (
                    SELECT schema_name, table_name, conname
                    FROM missing
                    ORDER BY schema_name, table_name, conname
                    LIMIT 5
                ) AS s
            ),
            'none'
        ) AS sample_fk
    FROM missing
) AS f

UNION ALL

SELECT
    'IDX-001',
    'Indexing',
    'MEDIUM',
    CASE WHEN d.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    d.issue_count,
    'No duplicate index definitions expected',
    CASE
        WHEN d.issue_count = 0 THEN 'No duplicate index groups'
        ELSE 'sample=' || d.sample_tables
    END,
    'Review duplicate indexes and drop redundant ones after workload verification.'
FROM (
    WITH idx AS (
        SELECT
            n.nspname AS schema_name,
            c.relname AS table_name,
            i.indrelid,
            i.indkey,
            i.indclass,
            i.indcollation,
            i.indoption,
            i.indpred,
            i.indexprs,
            i.indisunique,
            i.indisprimary
        FROM pg_index i
        JOIN pg_class c
            ON c.oid = i.indrelid
        JOIN pg_namespace n
            ON n.oid = c.relnamespace
        WHERE n.nspname !~ '^pg_'
          AND n.nspname <> 'information_schema'
    ),
    dup AS (
        SELECT
            schema_name,
            table_name
        FROM idx
        GROUP BY
            schema_name,
            table_name,
            indrelid,
            indkey,
            indclass,
            indcollation,
            indoption,
            indpred,
            indexprs,
            indisunique,
            indisprimary
        HAVING count(*) > 1
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('%I.%I', schema_name, table_name), ', ')
                FROM (
                    SELECT schema_name, table_name
                    FROM dup
                    ORDER BY schema_name, table_name
                    LIMIT 5
                ) AS s
            ),
            'none'
        ) AS sample_tables
    FROM dup
) AS d

UNION ALL

SELECT
    'NAM-001',
    'Migration Compatibility',
    'LOW',
    CASE WHEN n.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    n.issue_count,
    'Object names with uppercase letters require quoted SQL references',
    CASE
        WHEN n.issue_count = 0 THEN 'No uppercase object names'
        ELSE 'sample=' || n.sample_objects
    END,
    'Standardize names to lowercase where feasible to avoid quoting-related bugs.'
FROM (
    WITH upper_names AS (
        SELECT format('%I.%I', ns.nspname, c.relname) AS object_name
        FROM pg_class c
        JOIN pg_namespace ns
            ON ns.oid = c.relnamespace
        WHERE ns.nspname !~ '^pg_'
          AND ns.nspname <> 'information_schema'
          AND c.relkind IN ('r', 'p', 'v', 'm', 'S', 'f')
          AND c.relname ~ '[A-Z]'
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(object_name, ', ')
                FROM (
                    SELECT object_name
                    FROM upper_names
                    ORDER BY object_name
                    LIMIT 5
                ) AS s
            ),
            'none'
        ) AS sample_objects
    FROM upper_names
) AS n

UNION ALL

SELECT
    'OBJ-004',
    'Migration Compatibility',
    'MEDIUM',
    CASE WHEN s.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    s.issue_count,
    'Sequences should be owned by a target table column when used as identity/serial',
    CASE
        WHEN s.issue_count = 0 THEN 'No unowned sequences'
        ELSE 'sample=' || s.sample_sequences
    END,
    'Use ALTER SEQUENCE schema.seq OWNED BY schema.table.column where ownership is expected.'
FROM (
    WITH seq AS (
        SELECT
            c.oid,
            n.nspname,
            c.relname
        FROM pg_class c
        JOIN pg_namespace n
            ON n.oid = c.relnamespace
        WHERE c.relkind = 'S'
          AND n.nspname !~ '^pg_'
          AND n.nspname <> 'information_schema'
    ),
    unowned AS (
        SELECT
            nspname,
            relname
        FROM seq s
        WHERE NOT EXISTS (
            SELECT 1
            FROM pg_depend d
            WHERE d.objid = s.oid
              AND d.deptype IN ('a', 'i')
              AND d.refclassid = 'pg_class'::regclass
        )
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('%I.%I', nspname, relname), ', ')
                FROM (
                    SELECT nspname, relname
                    FROM unowned
                    ORDER BY nspname, relname
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_sequences
    FROM unowned
) AS s

UNION ALL

SELECT
    'ACT-001',
    'Activity and Locks',
    'CRITICAL',
    CASE WHEN b.issue_count = 0 THEN 'PASS' ELSE 'FAIL' END,
    b.issue_count,
    'No blocked sessions expected during normal operation',
    CASE
        WHEN b.issue_count = 0 THEN 'No blocked sessions'
        ELSE 'sample=' || b.sample_pairs
    END,
    'Investigate blocker SQL and lock chain; commit/rollback blocker or tune transaction scope.'
FROM (
    WITH blocked AS (
        SELECT
            a.pid AS blocked_pid,
            unnest(pg_blocking_pids(a.pid)) AS blocker_pid
        FROM pg_stat_activity a
        WHERE a.pid <> pg_backend_pid()
          AND array_length(pg_blocking_pids(a.pid), 1) > 0
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('blocked=%s by=%s', blocked_pid, blocker_pid), ', ')
                FROM (
                    SELECT blocked_pid, blocker_pid
                    FROM blocked
                    ORDER BY blocked_pid, blocker_pid
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_pairs
    FROM blocked
) AS b

UNION ALL

SELECT
    'ACT-002',
    'Activity and Locks',
    'CRITICAL',
    CASE WHEN x.issue_count = 0 THEN 'PASS' ELSE 'FAIL' END,
    x.issue_count,
    'Transactions longer than 30 minutes are risk candidates',
    CASE
        WHEN x.issue_count = 0 THEN 'No long transactions'
        ELSE 'sample=' || x.sample_pids
    END,
    'Break large transactions into batches and commit more frequently.'
FROM (
    WITH long_xacts AS (
        SELECT
            pid,
            now() - xact_start AS xact_age
        FROM pg_stat_activity
        WHERE xact_start IS NOT NULL
          AND pid <> pg_backend_pid()
          AND now() - xact_start > interval '30 minutes'
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('pid=%s age=%s', pid, xact_age), ', ')
                FROM (
                    SELECT pid, xact_age
                    FROM long_xacts
                    ORDER BY xact_age DESC
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_pids
    FROM long_xacts
) AS x

UNION ALL

SELECT
    'ACT-003',
    'Activity and Locks',
    'HIGH',
    CASE WHEN i.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    i.issue_count,
    'Idle in transaction sessions > 15 minutes should be zero',
    CASE
        WHEN i.issue_count = 0 THEN 'No idle in transaction offenders'
        ELSE 'sample=' || i.sample_pids
    END,
    'Ensure application transactions close quickly and enforce idle_in_transaction_session_timeout.'
FROM (
    WITH idle_tx AS (
        SELECT
            pid,
            now() - state_change AS idle_age
        FROM pg_stat_activity
        WHERE state = 'idle in transaction'
          AND pid <> pg_backend_pid()
          AND now() - state_change > interval '15 minutes'
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('pid=%s idle=%s', pid, idle_age), ', ')
                FROM (
                    SELECT pid, idle_age
                    FROM idle_tx
                    ORDER BY idle_age DESC
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_pids
    FROM idle_tx
) AS i

UNION ALL

SELECT
    'VAC-001',
    'Vacuum and Bloat',
    'HIGH',
    CASE WHEN v.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    v.issue_count,
    'Dead tuple pressure: table >= 100MB and dead_tuple_pct >= 20%',
    CASE
        WHEN v.issue_count = 0 THEN 'No high dead tuple tables'
        ELSE 'sample=' || v.sample_tables
    END,
    'Tune autovacuum thresholds/frequency and run targeted VACUUM (ANALYZE) on hot tables.'
FROM (
    WITH table_stats AS (
        SELECT
            s.schemaname,
            s.relname,
            s.n_live_tup,
            s.n_dead_tup,
            pg_total_relation_size(s.relid) AS total_bytes,
            round(100.0 * s.n_dead_tup / NULLIF(s.n_live_tup + s.n_dead_tup, 0), 2) AS dead_tuple_pct
        FROM pg_stat_user_tables s
    ),
    pressure AS (
        SELECT
            schemaname,
            relname,
            dead_tuple_pct
        FROM table_stats
        WHERE total_bytes >= 100::bigint * 1024 * 1024
          AND n_dead_tup >= 10000
          AND dead_tuple_pct >= 20
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('%I.%I(%s%%)', schemaname, relname, dead_tuple_pct), ', ')
                FROM (
                    SELECT schemaname, relname, dead_tuple_pct
                    FROM pressure
                    ORDER BY dead_tuple_pct DESC
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_tables
    FROM pressure
) AS v

UNION ALL

SELECT
    'VAC-002',
    'Vacuum and Bloat',
    'CRITICAL',
    CASE WHEN f.issue_count = 0 THEN 'PASS' ELSE 'FAIL' END,
    f.issue_count,
    'Freeze age risk: relfrozenxid age > 1.5B',
    CASE
        WHEN f.issue_count = 0 THEN 'No freeze-age risk tables'
        ELSE 'sample=' || f.sample_tables
    END,
    'Run aggressive vacuum/freeze cycle and verify autovacuum freeze settings.'
FROM (
    WITH freeze_risk AS (
        SELECT
            n.nspname,
            c.relname,
            age(c.relfrozenxid) AS xid_age
        FROM pg_class c
        JOIN pg_namespace n
            ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r', 'm')
          AND n.nspname !~ '^pg_'
          AND n.nspname <> 'information_schema'
          AND age(c.relfrozenxid) > 1500000000
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('%I.%I(age=%s)', nspname, relname, xid_age), ', ')
                FROM (
                    SELECT nspname, relname, xid_age
                    FROM freeze_risk
                    ORDER BY xid_age DESC
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_tables
    FROM freeze_risk
) AS f

UNION ALL

SELECT
    'STA-001',
    'Planner Statistics',
    'MEDIUM',
    CASE WHEN s.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    s.issue_count,
    'Stale stats: n_mod_since_analyze > 50000 and no analyze in last 1 day',
    CASE
        WHEN s.issue_count = 0 THEN 'No stale statistics hotspots'
        ELSE 'sample=' || s.sample_tables
    END,
    'Run ANALYZE on changing tables and tune autovacuum_analyze thresholds.'
FROM (
    WITH stale AS (
        SELECT
            schemaname,
            relname,
            n_mod_since_analyze,
            GREATEST(last_analyze, last_autoanalyze) AS last_any_analyze
        FROM pg_stat_user_tables
        WHERE n_mod_since_analyze > 50000
    )
    SELECT
        count(*) FILTER (
            WHERE last_any_analyze IS NULL
               OR now() - last_any_analyze > interval '1 day'
        )::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('%I.%I(mods=%s)', schemaname, relname, n_mod_since_analyze), ', ')
                FROM (
                    SELECT schemaname, relname, n_mod_since_analyze
                    FROM stale
                    WHERE last_any_analyze IS NULL
                       OR now() - last_any_analyze > interval '1 day'
                    ORDER BY n_mod_since_analyze DESC
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_tables
    FROM stale
) AS s

UNION ALL

SELECT
    'CAP-001',
    'Capacity',
    'HIGH',
    CASE
        WHEN c.usage_pct >= 95 THEN 'FAIL'
        WHEN c.usage_pct >= 85 THEN 'WARN'
        ELSE 'PASS'
    END,
    CASE
        WHEN c.usage_pct >= 85 THEN 1
        ELSE 0
    END,
    'Connection usage warn >= 85%, fail >= 95%',
    'current=' || c.current_connections
    || ' max=' || c.max_connections
    || ' usage_pct=' || c.usage_pct,
    'Use connection pooling, tune app concurrency, or increase max_connections only with memory planning.'
FROM (
    WITH raw AS (
        SELECT
            (SELECT count(*) FROM pg_stat_activity)::numeric AS current_connections,
            (SELECT setting::numeric FROM pg_settings WHERE name = 'max_connections') AS max_connections
    )
    SELECT
        current_connections,
        max_connections,
        round(100.0 * current_connections / NULLIF(max_connections, 0), 2) AS usage_pct
    FROM raw
) AS c

UNION ALL

SELECT
    'IO-001',
    'I/O and Cache',
    'MEDIUM',
    CASE WHEN io.cache_hit_ratio >= 0.95 THEN 'PASS' ELSE 'WARN' END,
    CASE WHEN io.cache_hit_ratio >= 0.95 THEN 0 ELSE 1 END,
    'Global cache hit ratio should be >= 95%',
    'cache_hit_ratio=' || round(io.cache_hit_ratio::numeric, 4),
    'Investigate index/query patterns and memory sizing (shared_buffers/effective_cache_size).'
FROM (
    WITH agg AS (
        SELECT
            COALESCE(sum(blks_hit), 0)::numeric AS blks_hit,
            COALESCE(sum(blks_read), 0)::numeric AS blks_read
        FROM pg_stat_database
        WHERE datname NOT IN ('template0', 'template1')
    )
    SELECT
        COALESCE(blks_hit / NULLIF(blks_hit + blks_read, 0), 1.0) AS cache_hit_ratio
    FROM agg
) AS io

UNION ALL

SELECT
    'WAL-001',
    'WAL and Checkpoints',
    'MEDIUM',
    CASE WHEN w.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    w.issue_count,
    'Recommended baseline: max_wal_size >= 4GB, checkpoint_timeout >= 10min, checkpoint_completion_target >= 0.90',
    w.evidence,
    'Tune WAL/checkpoint settings based on write rate and storage throughput.'
FROM (
    WITH raw AS (
        SELECT
            (SELECT setting::numeric FROM pg_settings WHERE name = 'max_wal_size') AS max_wal_size_value,
            (SELECT unit FROM pg_settings WHERE name = 'max_wal_size') AS max_wal_size_unit,
            (SELECT setting::numeric FROM pg_settings WHERE name = 'checkpoint_timeout') AS checkpoint_timeout_value,
            (SELECT unit FROM pg_settings WHERE name = 'checkpoint_timeout') AS checkpoint_timeout_unit,
            (SELECT setting::numeric FROM pg_settings WHERE name = 'checkpoint_completion_target') AS checkpoint_completion_target
    ),
    normalized AS (
        SELECT
            CASE
                WHEN max_wal_size_unit = 'kB' THEN max_wal_size_value * 1024
                WHEN max_wal_size_unit = '8kB' THEN max_wal_size_value * 8192
                WHEN max_wal_size_unit = 'MB' THEN max_wal_size_value * 1024 * 1024
                WHEN max_wal_size_unit = 'GB' THEN max_wal_size_value * 1024 * 1024 * 1024
                WHEN max_wal_size_unit = 'B' THEN max_wal_size_value
                ELSE max_wal_size_value
            END AS max_wal_size_bytes,
            CASE
                WHEN checkpoint_timeout_unit = 'ms' THEN checkpoint_timeout_value / 1000
                WHEN checkpoint_timeout_unit = 's' THEN checkpoint_timeout_value
                WHEN checkpoint_timeout_unit = 'min' THEN checkpoint_timeout_value * 60
                ELSE checkpoint_timeout_value
            END AS checkpoint_timeout_seconds,
            checkpoint_completion_target
        FROM raw
    )
    SELECT
        (
            CASE
                WHEN max_wal_size_bytes < (4::numeric * 1024 * 1024 * 1024) THEN 1
                ELSE 0
            END
            +
            CASE
                WHEN checkpoint_timeout_seconds < 600 THEN 1
                ELSE 0
            END
            +
            CASE
                WHEN checkpoint_completion_target < 0.90 THEN 1
                ELSE 0
            END
        )::bigint AS issue_count,
        'max_wal_size=' || pg_size_pretty(max_wal_size_bytes::bigint)
        || ', checkpoint_timeout=' || round(checkpoint_timeout_seconds)::bigint || 's'
        || ', checkpoint_completion_target=' || checkpoint_completion_target AS evidence
    FROM normalized
) AS w

UNION ALL

SELECT
    'REP-001',
    'Replication and HA',
    'HIGH',
    CASE
        WHEN r.in_recovery THEN 'PASS'
        WHEN r.standby_count = 0 THEN 'WARN'
        WHEN r.max_lag_bytes > (5::numeric * 1024 * 1024 * 1024) THEN 'FAIL'
        WHEN r.max_lag_bytes > (1::numeric * 1024 * 1024 * 1024) THEN 'WARN'
        ELSE 'PASS'
    END,
    CASE
        WHEN r.in_recovery THEN 0
        WHEN r.standby_count = 0 THEN 1
        WHEN r.max_lag_bytes > (1::numeric * 1024 * 1024 * 1024) THEN 1
        ELSE 0
    END,
    'Primary lag threshold: warn > 1GB, fail > 5GB',
    CASE
        WHEN r.in_recovery THEN 'Node is standby; lag-to-standby check not applicable'
        ELSE format(
            'standbys=%s max_lag=%s',
            r.standby_count,
            pg_size_pretty(r.max_lag_bytes::bigint)
        )
    END,
    'Check network/WAL sender-receiver health, standby replay speed, and disk I/O on replicas.'
FROM (
    WITH base AS (
        SELECT
            pg_is_in_recovery() AS in_recovery,
            CASE
                WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn()
                ELSE pg_current_wal_lsn()
            END AS base_lsn
    )
    SELECT
        b.in_recovery,
        count(s.*)::bigint AS standby_count,
        COALESCE(max(pg_wal_lsn_diff(b.base_lsn, s.replay_lsn)), 0)::numeric AS max_lag_bytes
    FROM base b
    LEFT JOIN pg_stat_replication s
        ON TRUE
    GROUP BY b.in_recovery, b.base_lsn
) AS r

UNION ALL

SELECT
    'REP-002',
    'Replication and HA',
    'HIGH',
    CASE WHEN s.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    s.issue_count,
    'Replication slot retained WAL should stay below 5GB',
    CASE
        WHEN s.issue_count = 0 THEN 'No excessive slot WAL retention'
        ELSE 'sample=' || s.sample_slots
    END,
    'Advance/drop stale slots and verify consumers to avoid WAL disk pressure.'
FROM (
    WITH base AS (
        SELECT CASE
            WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn()
            ELSE pg_current_wal_lsn()
        END AS base_lsn
    ),
    slot_retention AS (
        SELECT
            rs.slot_name,
            GREATEST(pg_wal_lsn_diff(b.base_lsn, rs.restart_lsn), 0)::numeric AS retained_bytes
        FROM base b
        JOIN pg_replication_slots rs
            ON rs.restart_lsn IS NOT NULL
    ),
    offenders AS (
        SELECT
            slot_name,
            retained_bytes
        FROM slot_retention
        WHERE retained_bytes > (5::numeric * 1024 * 1024 * 1024)
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(
                    format('%I(%s)', slot_name, pg_size_pretty(retained_bytes::bigint)),
                    ', '
                )
                FROM (
                    SELECT slot_name, retained_bytes
                    FROM offenders
                    ORDER BY retained_bytes DESC
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_slots
    FROM offenders
) AS s

UNION ALL

SELECT
    'STO-001',
    'Storage',
    'MEDIUM',
    CASE WHEN t.issue_count = 0 THEN 'PASS' ELSE 'WARN' END,
    t.issue_count,
    'TOAST-heavy tables: total_size >= 100MB and toast_pct > 50%',
    CASE
        WHEN t.issue_count = 0 THEN 'No TOAST-heavy tables'
        ELSE 'sample=' || t.sample_tables
    END,
    'Evaluate schema/model choices and compression strategy for large varlena columns.'
FROM (
    WITH table_sizes AS (
        SELECT
            n.nspname AS schema_name,
            c.relname AS table_name,
            pg_total_relation_size(c.oid) AS total_bytes,
            CASE
                WHEN c.reltoastrelid = 0 THEN 0::bigint
                ELSE pg_total_relation_size(c.reltoastrelid)
            END AS toast_bytes
        FROM pg_class c
        JOIN pg_namespace n
            ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r', 'm')
          AND n.nspname !~ '^pg_'
          AND n.nspname <> 'information_schema'
    ),
    heavy AS (
        SELECT
            schema_name,
            table_name,
            round(100.0 * toast_bytes / NULLIF(total_bytes, 0), 2) AS toast_pct
        FROM table_sizes
        WHERE total_bytes >= 100::bigint * 1024 * 1024
          AND toast_bytes > 0
          AND toast_bytes::numeric / NULLIF(total_bytes, 0) > 0.50
    )
    SELECT
        count(*)::bigint AS issue_count,
        COALESCE(
            (
                SELECT string_agg(format('%I.%I(%s%%)', schema_name, table_name, toast_pct), ', ')
                FROM (
                    SELECT schema_name, table_name, toast_pct
                    FROM heavy
                    ORDER BY toast_pct DESC
                    LIMIT 5
                ) AS t
            ),
            'none'
        ) AS sample_tables
    FROM heavy
) AS t;

CREATE TEMP TABLE tmp_pg360_issue_details (
    check_id text NOT NULL,
    object_type text NOT NULL,
    object_name text NOT NULL,
    metric numeric,
    details text NOT NULL,
    recommended_fix text NOT NULL
);

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'OBJ-001',
    'INDEX',
    format('%I.%I', n.nspname, c.relname),
    NULL::numeric,
    format('indisvalid=%s indisready=%s', i.indisvalid, i.indisready),
    'Rebuild index (REINDEX INDEX CONCURRENTLY where possible).'
FROM pg_index i
JOIN pg_class c
    ON c.oid = i.indexrelid
JOIN pg_namespace n
    ON n.oid = c.relnamespace
WHERE n.nspname !~ '^pg_'
  AND n.nspname <> 'information_schema'
  AND (NOT i.indisvalid OR NOT i.indisready)
ORDER BY 3
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'OBJ-002',
    'TABLE',
    format('%I.%I', n.nspname, c.relname),
    pg_total_relation_size(c.oid)::numeric,
    'table_size=' || pg_size_pretty(pg_total_relation_size(c.oid)),
    'Define and backfill a primary key after validating uniqueness.'
FROM pg_class c
JOIN pg_namespace n
    ON n.oid = c.relnamespace
WHERE c.relkind = 'r'
  AND n.nspname !~ '^pg_'
  AND n.nspname <> 'information_schema'
  AND NOT EXISTS (
      SELECT 1
      FROM pg_constraint p
      WHERE p.conrelid = c.oid
        AND p.contype = 'p'
  )
ORDER BY pg_total_relation_size(c.oid) DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
WITH fk AS (
    SELECT
        c.conname,
        c.conrelid,
        c.conkey,
        n.nspname,
        t.relname
    FROM pg_constraint c
    JOIN pg_class t
        ON t.oid = c.conrelid
    JOIN pg_namespace n
        ON n.oid = t.relnamespace
    WHERE c.contype = 'f'
      AND n.nspname !~ '^pg_'
      AND n.nspname <> 'information_schema'
)
SELECT
    'OBJ-003',
    'FOREIGN KEY',
    format('%I.%I(%I)', fk.nspname, fk.relname, fk.conname),
    NULL::numeric,
    'fk_columns_attnum=' || array_to_string(fk.conkey, ','),
    'Create a supporting index with FK columns as leading columns.'
FROM fk
WHERE NOT EXISTS (
    SELECT 1
    FROM pg_index i
    WHERE i.indrelid = fk.conrelid
      AND i.indisvalid
      AND i.indisready
      AND (
          SELECT array_agg(k.attnum ORDER BY k.ord)
          FROM unnest(i.indkey::smallint[]) WITH ORDINALITY AS k(attnum, ord)
          WHERE k.ord <= array_length(fk.conkey, 1)
      ) = fk.conkey
)
ORDER BY 3
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
WITH idx AS (
    SELECT
        n.nspname AS schema_name,
        c.relname AS table_name,
        ci.relname AS index_name,
        i.indrelid,
        i.indkey,
        i.indclass,
        i.indcollation,
        i.indoption,
        i.indpred,
        i.indexprs,
        i.indisunique,
        i.indisprimary
    FROM pg_index i
    JOIN pg_class c
        ON c.oid = i.indrelid
    JOIN pg_class ci
        ON ci.oid = i.indexrelid
    JOIN pg_namespace n
        ON n.oid = c.relnamespace
    WHERE n.nspname !~ '^pg_'
      AND n.nspname <> 'information_schema'
),
dup AS (
    SELECT
        schema_name,
        table_name,
        count(*) AS duplicate_count,
        string_agg(index_name, ', ' ORDER BY index_name) AS duplicate_indexes
    FROM idx
    GROUP BY
        schema_name,
        table_name,
        indrelid,
        indkey,
        indclass,
        indcollation,
        indoption,
        indpred,
        indexprs,
        indisunique,
        indisprimary
    HAVING count(*) > 1
)
SELECT
    'IDX-001',
    'TABLE',
    format('%I.%I', schema_name, table_name),
    duplicate_count::numeric,
    'duplicate_indexes=' || duplicate_indexes,
    'Drop redundant index(es) only after plan/workload validation.'
FROM dup
ORDER BY duplicate_count DESC, schema_name, table_name
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
WITH blocked AS (
    SELECT
        blocked.pid AS blocked_pid,
        blocked.usename AS blocked_user,
        blocker.pid AS blocker_pid,
        blocker.usename AS blocker_user,
        EXTRACT(EPOCH FROM (now() - blocked.query_start))::numeric AS blocked_seconds
    FROM pg_stat_activity blocked
    CROSS JOIN LATERAL unnest(pg_blocking_pids(blocked.pid)) AS p(blocker_pid)
    JOIN pg_stat_activity blocker
        ON blocker.pid = p.blocker_pid
)
SELECT
    'ACT-001',
    'SESSION',
    format('blocked_pid=%s', blocked_pid),
    blocked_seconds,
    format('blocked_user=%s blocker_pid=%s blocker_user=%s', blocked_user, blocker_pid, blocker_user),
    'Shorten transaction scope or terminate blocker after impact analysis.'
FROM blocked
ORDER BY blocked_seconds DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'ACT-002',
    'SESSION',
    format('pid=%s', pid),
    EXTRACT(EPOCH FROM (now() - xact_start))::numeric AS xact_seconds,
    format('user=%s app=%s state=%s', usename, application_name, state),
    'Break large work into smaller transactions and commit faster.'
FROM pg_stat_activity
WHERE xact_start IS NOT NULL
  AND pid <> pg_backend_pid()
  AND now() - xact_start > interval '30 minutes'
ORDER BY xact_seconds DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'ACT-003',
    'SESSION',
    format('pid=%s', pid),
    EXTRACT(EPOCH FROM (now() - state_change))::numeric AS idle_seconds,
    format('user=%s app=%s', usename, application_name),
    'Fix app transaction lifecycle and set idle_in_transaction_session_timeout.'
FROM pg_stat_activity
WHERE state = 'idle in transaction'
  AND pid <> pg_backend_pid()
  AND now() - state_change > interval '15 minutes'
ORDER BY idle_seconds DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'VAC-001',
    'TABLE',
    format('%I.%I', s.schemaname, s.relname),
    round(100.0 * s.n_dead_tup / NULLIF(s.n_live_tup + s.n_dead_tup, 0), 2),
    format(
        'dead=%s live=%s total_size=%s',
        s.n_dead_tup,
        s.n_live_tup,
        pg_size_pretty(pg_total_relation_size(s.relid))
    ),
    'Tune autovacuum and vacuum this table during low-traffic windows.'
FROM pg_stat_user_tables s
WHERE pg_total_relation_size(s.relid) >= 100::bigint * 1024 * 1024
  AND s.n_dead_tup >= 10000
  AND round(100.0 * s.n_dead_tup / NULLIF(s.n_live_tup + s.n_dead_tup, 0), 2) >= 20
ORDER BY round(100.0 * s.n_dead_tup / NULLIF(s.n_live_tup + s.n_dead_tup, 0), 2) DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'VAC-002',
    'TABLE',
    format('%I.%I', n.nspname, c.relname),
    age(c.relfrozenxid)::numeric,
    'total_size=' || pg_size_pretty(pg_total_relation_size(c.oid)),
    'Run VACUUM (FREEZE) and review autovacuum freeze settings.'
FROM pg_class c
JOIN pg_namespace n
    ON n.oid = c.relnamespace
WHERE c.relkind IN ('r', 'm')
  AND n.nspname !~ '^pg_'
  AND n.nspname <> 'information_schema'
  AND age(c.relfrozenxid) > 1500000000
ORDER BY age(c.relfrozenxid) DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'STA-001',
    'TABLE',
    format('%I.%I', schemaname, relname),
    n_mod_since_analyze::numeric,
    format(
        'last_any_analyze=%s',
        COALESCE(GREATEST(last_analyze, last_autoanalyze)::text, 'never')
    ),
    'Run ANALYZE and tune autoanalyze thresholds for this table.'
FROM pg_stat_user_tables
WHERE n_mod_since_analyze > 50000
  AND (
      GREATEST(last_analyze, last_autoanalyze) IS NULL
      OR now() - GREATEST(last_analyze, last_autoanalyze) > interval '1 day'
  )
ORDER BY n_mod_since_analyze DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'REP-001',
    'STANDBY',
    COALESCE(application_name, '<unknown_app>') || '@' || COALESCE(client_addr::text, '<unknown_ip>'),
    pg_wal_lsn_diff(
        CASE
            WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn()
            ELSE pg_current_wal_lsn()
        END,
        replay_lsn
    )::numeric AS lag_bytes,
    format('state=%s sync_state=%s', state, sync_state),
    'Investigate network and standby replay bottlenecks.'
FROM pg_stat_replication
WHERE pg_wal_lsn_diff(
          CASE
              WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn()
              ELSE pg_current_wal_lsn()
          END,
          replay_lsn
      ) > (1::numeric * 1024 * 1024 * 1024)
ORDER BY lag_bytes DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
WITH base AS (
    SELECT CASE
        WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn()
        ELSE pg_current_wal_lsn()
    END AS base_lsn
)
SELECT
    'REP-002',
    'REPLICATION SLOT',
    rs.slot_name,
    GREATEST(pg_wal_lsn_diff(b.base_lsn, rs.restart_lsn), 0)::numeric AS retained_bytes,
    format('slot_type=%s active=%s', rs.slot_type, rs.active),
    'Advance/drop stale slot and validate consumer status.'
FROM base b
JOIN pg_replication_slots rs
    ON rs.restart_lsn IS NOT NULL
WHERE GREATEST(pg_wal_lsn_diff(b.base_lsn, rs.restart_lsn), 0)::numeric > (5::numeric * 1024 * 1024 * 1024)
ORDER BY retained_bytes DESC
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'NAM-001',
    'OBJECT',
    format('%I.%I', n.nspname, c.relname),
    NULL::numeric,
    'Contains uppercase characters',
    'Prefer lowercase object names to avoid quote-sensitive SQL behavior.'
FROM pg_class c
JOIN pg_namespace n
    ON n.oid = c.relnamespace
WHERE n.nspname !~ '^pg_'
  AND n.nspname <> 'information_schema'
  AND c.relkind IN ('r', 'p', 'v', 'm', 'S', 'f')
  AND c.relname ~ '[A-Z]'
ORDER BY 3
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
SELECT
    'OBJ-004',
    'SEQUENCE',
    format('%I.%I', n.nspname, c.relname),
    NULL::numeric,
    'No OWNED BY dependency detected',
    'Use ALTER SEQUENCE ... OWNED BY ... when sequence should be tied to a column.'
FROM pg_class c
JOIN pg_namespace n
    ON n.oid = c.relnamespace
WHERE c.relkind = 'S'
  AND n.nspname !~ '^pg_'
  AND n.nspname <> 'information_schema'
  AND NOT EXISTS (
      SELECT 1
      FROM pg_depend d
      WHERE d.objid = c.oid
        AND d.deptype IN ('a', 'i')
        AND d.refclassid = 'pg_class'::regclass
  )
ORDER BY 3
LIMIT 50;

INSERT INTO tmp_pg360_issue_details (
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
)
WITH table_sizes AS (
    SELECT
        n.nspname,
        c.relname,
        pg_total_relation_size(c.oid) AS total_bytes,
        CASE
            WHEN c.reltoastrelid = 0 THEN 0::bigint
            ELSE pg_total_relation_size(c.reltoastrelid)
        END AS toast_bytes
    FROM pg_class c
    JOIN pg_namespace n
        ON n.oid = c.relnamespace
    WHERE c.relkind IN ('r', 'm')
      AND n.nspname !~ '^pg_'
      AND n.nspname <> 'information_schema'
)
SELECT
    'STO-001',
    'TABLE',
    format('%I.%I', nspname, relname),
    round(100.0 * toast_bytes / NULLIF(total_bytes, 0), 2),
    format(
        'total=%s toast=%s',
        pg_size_pretty(total_bytes),
        pg_size_pretty(toast_bytes)
    ),
    'Review large text/json/blob model and compression strategy.'
FROM table_sizes
WHERE total_bytes >= 100::bigint * 1024 * 1024
  AND toast_bytes > 0
  AND toast_bytes::numeric / NULLIF(total_bytes, 0) > 0.50
ORDER BY round(100.0 * toast_bytes / NULLIF(total_bytes, 0), 2) DESC
LIMIT 50;

\unset QUIET

\pset title 'Overall Health Summary'
SELECT
    count(*) AS total_checks,
    count(*) FILTER (WHERE status = 'PASS') AS passed_checks,
    count(*) FILTER (WHERE status = 'WARN') AS warning_checks,
    count(*) FILTER (WHERE status = 'FAIL') AS failed_checks,
    CASE
        WHEN count(*) FILTER (WHERE status = 'FAIL') = 0 THEN 'YES'
        ELSE 'NO'
    END AS all_critical_checks_passed
FROM tmp_pg360_check_results;

\pset title '360-Degree Check Results'
SELECT
    check_id,
    area,
    status,
    severity_if_failing,
    issue_count,
    threshold_rule,
    evidence,
    recommended_fix
FROM tmp_pg360_check_results
ORDER BY
    CASE status
        WHEN 'FAIL' THEN 1
        WHEN 'WARN' THEN 2
        ELSE 3
    END,
    check_id;

\pset title 'Issue Details (Top Objects and Sessions)'
SELECT
    check_id,
    object_type,
    object_name,
    metric,
    details,
    recommended_fix
FROM tmp_pg360_issue_details
ORDER BY check_id, metric DESC NULLS LAST, object_name;

\qecho </body>
\qecho </html>

\o
\pset format aligned
\echo HTML report written to :report_file




-- SAMPLE_OUTPUT_BEGIN
-- Sample output captured from database: pgbench_test
-- Capture run directory: /tmp/pgbench_full_refresh_clean_20260218_194330
--
-- Pager usage is off.
-- Border style is 1.
-- Output format is html.
-- Title is "Report Metadata".
-- Title is "Overall Health Summary".
-- Title is "360-Degree Check Results".
-- Title is "Issue Details (Top Objects and Sessions)".
-- Output format is aligned.
-- HTML report written to postgres_360_migration_health_report.html
-- SAMPLE_OUTPUT_END
