/*
Purpose: Seed deterministic Oracle->PostgreSQL migration issues for V1 report validation.
Area: Migration Validation
Usage:
  psql "host=<host> port=<port> dbname=<db> user=<user>" \
    -f 27_migration_validation/02_seed_v1_test_issues.sql

Notes:
  - Creates schema migration_v1_lab and inserts test-only data.
  - Safe to rerun: drops and recreates migration_v1_lab.
*/

\set ON_ERROR_STOP on
\pset pager off

\echo [V1 seed] Recreating migration_v1_lab schema...
DROP SCHEMA IF EXISTS migration_v1_lab CASCADE;
CREATE SCHEMA migration_v1_lab;

\echo [V1 seed] Creating table without primary key...
CREATE TABLE migration_v1_lab.orders_no_pk (
    order_id bigint NOT NULL,
    customer_name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v1_lab.orders_no_pk (order_id, customer_name)
SELECT
    gs,
    'customer_' || gs
FROM generate_series(1, 10000) AS gs;

\echo [V1 seed] Creating unowned sequence...
CREATE SEQUENCE migration_v1_lab.orphan_seq START WITH 1 INCREMENT BY 1;
SELECT nextval('migration_v1_lab.orphan_seq') FROM generate_series(1, 20);

\echo [V1 seed] Creating FK without supporting index...
CREATE TABLE migration_v1_lab.parent_accounts (
    account_id bigint PRIMARY KEY,
    account_name text NOT NULL
);

CREATE TABLE migration_v1_lab.child_transactions (
    txn_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES migration_v1_lab.parent_accounts(account_id),
    amount numeric(12,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v1_lab.parent_accounts (account_id, account_name)
SELECT
    gs,
    'acct_' || gs
FROM generate_series(1, 10000) AS gs;

INSERT INTO migration_v1_lab.child_transactions (account_id, amount)
SELECT
    (1 + (random() * 9999)::int)::bigint,
    round((random() * 2000)::numeric, 2)
FROM generate_series(1, 120000);

\echo [V1 seed] Creating duplicate indexes...
CREATE TABLE migration_v1_lab.product_catalog (
    product_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sku text NOT NULL,
    category text NOT NULL,
    price numeric(10,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v1_lab.product_catalog (sku, category, price)
SELECT
    'sku_' || gs,
    CASE
        WHEN gs % 5 = 0 THEN 'A'
        WHEN gs % 5 = 1 THEN 'B'
        WHEN gs % 5 = 2 THEN 'C'
        WHEN gs % 5 = 3 THEN 'D'
        ELSE 'E'
    END,
    round((10 + random() * 500)::numeric, 2)
FROM generate_series(1, 50000) AS gs;

CREATE INDEX idx_product_sku_a ON migration_v1_lab.product_catalog (sku);
CREATE INDEX idx_product_sku_b ON migration_v1_lab.product_catalog (sku);

\echo [V1 seed] Creating uppercase object name...
CREATE TABLE migration_v1_lab."SalesOrders" (
    sales_order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notes text
);

INSERT INTO migration_v1_lab."SalesOrders" (notes)
SELECT 'sample_note_' || gs
FROM generate_series(1, 1000) AS gs;

\echo [V1 seed] Creating stale-stats table...
CREATE TABLE migration_v1_lab.stale_stats_table (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payload text NOT NULL
);

ALTER TABLE migration_v1_lab.stale_stats_table
    SET (autovacuum_enabled = off, toast.autovacuum_enabled = off);

INSERT INTO migration_v1_lab.stale_stats_table (payload)
SELECT md5(random()::text) || md5((random() * 999999)::text)
FROM generate_series(1, 60000);

\echo [V1 seed] Creating dead-tuple pressure table...
CREATE TABLE migration_v1_lab.dml_bloat_table (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payload text NOT NULL
);

ALTER TABLE migration_v1_lab.dml_bloat_table
    SET (autovacuum_enabled = off, toast.autovacuum_enabled = off);

INSERT INTO migration_v1_lab.dml_bloat_table (payload)
SELECT repeat(md5(gs::text), 180)
FROM generate_series(1, 25000) AS gs;

DELETE FROM migration_v1_lab.dml_bloat_table
WHERE id <= 13000;

\echo [V1 seed] Refreshing planner stats (without vacuum cleanup)...
ANALYZE migration_v1_lab.orders_no_pk;
ANALYZE migration_v1_lab.parent_accounts;
ANALYZE migration_v1_lab.child_transactions;
ANALYZE migration_v1_lab.product_catalog;
ANALYZE migration_v1_lab."SalesOrders";
-- Intentionally skip ANALYZE on stale_stats_table to trigger stale-stats risk.
-- Intentionally skip ANALYZE on dml_bloat_table to preserve dead-tuple pressure signal.

\echo [V1 seed] Seed complete.
