/*
Purpose: Seed practical, deterministic migration/performance issues using a dedicated lab schema.
Area: Migration Validation
Usage:
  psql "host=<host> port=<port> dbname=<db> user=<user>" \
    -f 27_migration_validation/05_seed_v2_test_issues.sql

Notes:
  - Creates schema migration_v2_lab and test-only objects.
  - Designed to be practical for pgbench-like workloads.
  - Safe to rerun: drops and recreates migration_v2_lab.
*/

\set ON_ERROR_STOP on
\pset pager off

\echo [V2 seed] Recreating migration_v2_lab schema...
DROP SCHEMA IF EXISTS migration_v2_lab CASCADE;
CREATE SCHEMA migration_v2_lab;

CREATE TABLE migration_v2_lab.issue_manifest (
    issue_id text PRIMARY KEY,
    issue_name text NOT NULL,
    severity text NOT NULL,
    seeded_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v2_lab.issue_manifest (issue_id, issue_name, severity)
VALUES
('MV2-OBJ-001', 'Missing primary key', 'CRITICAL'),
('MV2-OBJ-002', 'FK without supporting index', 'HIGH'),
('MV2-OBJ-003', 'Duplicate index definitions', 'MEDIUM'),
('MV2-OBJ-004', 'Uppercase quoted object names', 'MEDIUM'),
('MV2-OBJ-005', 'Orphan sequence (unowned)', 'HIGH'),
('MV2-STAT-001', 'Stale statistics risk', 'HIGH'),
('MV2-MAINT-001', 'Dead tuple / bloat pressure', 'HIGH'),
('MV2-DATA-001', 'Oracle empty-string semantic mismatch', 'HIGH'),
('MV2-DATA-002', 'Numeric overflow mapping risk', 'HIGH'),
('MV2-PERF-001', 'Missing index on join/filter column', 'MEDIUM'),
('MV2-PERF-002', 'Search path without functional index', 'MEDIUM');

\echo [V2 seed] Creating table without PK...
CREATE TABLE migration_v2_lab.customer_staging_no_pk (
    staging_id bigint NOT NULL,
    customer_name text NOT NULL,
    region_code text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v2_lab.customer_staging_no_pk (staging_id, customer_name, region_code)
SELECT
    gs,
    'cust_' || gs,
    CASE WHEN gs % 4 = 0 THEN 'NA' WHEN gs % 4 = 1 THEN 'EU' WHEN gs % 4 = 2 THEN 'APAC' ELSE 'LATAM' END
FROM generate_series(1, 60000) AS gs;

\echo [V2 seed] Creating orphan sequence...
CREATE SEQUENCE migration_v2_lab.orphan_order_seq START WITH 1 INCREMENT BY 1;
SELECT nextval('migration_v2_lab.orphan_order_seq') FROM generate_series(1, 25);

\echo [V2 seed] Creating parent-child tables with FK missing index...
CREATE TABLE migration_v2_lab.parent_accounts (
    account_id bigint PRIMARY KEY,
    account_name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE migration_v2_lab.child_events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES migration_v2_lab.parent_accounts(account_id),
    event_type text NOT NULL,
    amount numeric(12,2) NOT NULL,
    event_ts timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v2_lab.parent_accounts (account_id, account_name)
SELECT gs, 'acct_' || gs
FROM generate_series(1, 50000) AS gs;

INSERT INTO migration_v2_lab.child_events (account_id, event_type, amount)
SELECT
    (1 + (random() * 49999)::int)::bigint,
    CASE WHEN gs % 3 = 0 THEN 'PAY' WHEN gs % 3 = 1 THEN 'REVERSAL' ELSE 'FEE' END,
    round((random() * 5000)::numeric, 2)
FROM generate_series(1, 250000) AS gs;

\echo [V2 seed] Creating duplicate indexes...
CREATE TABLE migration_v2_lab.sales_catalog (
    catalog_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_ref text NOT NULL,
    item_type text NOT NULL,
    price numeric(10,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v2_lab.sales_catalog (item_ref, item_type, price)
SELECT
    'item_' || gs,
    CASE WHEN gs % 5 = 0 THEN 'A' WHEN gs % 5 = 1 THEN 'B' WHEN gs % 5 = 2 THEN 'C' WHEN gs % 5 = 3 THEN 'D' ELSE 'E' END,
    round((10 + random() * 700)::numeric, 2)
FROM generate_series(1, 120000) AS gs;

CREATE INDEX idx_v2_sales_ref_a ON migration_v2_lab.sales_catalog (item_ref);
CREATE INDEX idx_v2_sales_ref_b ON migration_v2_lab.sales_catalog (item_ref);

\echo [V2 seed] Creating uppercase object name...
CREATE TABLE migration_v2_lab."QuotedOrders" (
    quoted_order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v2_lab."QuotedOrders" (notes)
SELECT 'quoted_note_' || gs
FROM generate_series(1, 5000) AS gs;

\echo [V2 seed] Creating stale stats table...
CREATE TABLE migration_v2_lab.stale_stats_table (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payload text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE migration_v2_lab.stale_stats_table
    SET (autovacuum_enabled = off, toast.autovacuum_enabled = off);

INSERT INTO migration_v2_lab.stale_stats_table (payload)
SELECT md5(random()::text) || md5((random() * 999999)::text)
FROM generate_series(1, 180000);

\echo [V2 seed] Creating bloat pressure table...
CREATE TABLE migration_v2_lab.bloat_pressure_table (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payload text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE migration_v2_lab.bloat_pressure_table
    SET (autovacuum_enabled = off, toast.autovacuum_enabled = off);

INSERT INTO migration_v2_lab.bloat_pressure_table (payload)
SELECT repeat(md5(gs::text), 120)
FROM generate_series(1, 90000) AS gs;

DELETE FROM migration_v2_lab.bloat_pressure_table
WHERE id <= 48000;

\echo [V2 seed] Creating empty-string semantic mismatch dataset...
CREATE TABLE migration_v2_lab.customer_contact_compat (
    customer_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email text,
    phone text,
    comments text
);

INSERT INTO migration_v2_lab.customer_contact_compat (email, phone, comments)
SELECT
    CASE WHEN gs % 4 = 0 THEN '' ELSE 'user_' || gs || '@mail.test' END,
    CASE WHEN gs % 3 = 0 THEN '' ELSE '+1-555-' || lpad((gs % 10000)::text, 4, '0') END,
    CASE WHEN gs % 7 = 0 THEN '' ELSE 'ok' END
FROM generate_series(1, 90000) AS gs;

\echo [V2 seed] Creating numeric mapping risk dataset...
CREATE TABLE migration_v2_lab.amount_mapping_risk (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_numeric numeric(20,2) NOT NULL,
    target_int4_model int,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v2_lab.amount_mapping_risk (source_numeric, target_int4_model)
SELECT
    CASE
        WHEN gs % 10 = 0 THEN 3000000000 + gs
        WHEN gs % 10 = 1 THEN -3000000000 - gs
        ELSE gs::numeric
    END,
    NULL
FROM generate_series(1, 120000) AS gs;

\echo [V2 seed] Creating join/filter and search performance candidates...
CREATE TABLE migration_v2_lab.order_fact (
    order_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    filter_key int NOT NULL,
    search_text text NOT NULL,
    order_amount numeric(12,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO migration_v2_lab.order_fact (account_id, filter_key, search_text, order_amount)
SELECT
    (1 + (random() * 49999)::int)::bigint,
    (1 + (random() * 200)::int),
    CASE WHEN gs % 11 = 0 THEN 'urgent payment review ' || gs ELSE 'regular order note ' || gs END,
    round((50 + random() * 3000)::numeric, 2)
FROM generate_series(1, 300000) AS gs;

\echo [V2 seed] Creating view/mview/function/procedure/trigger/partition/type/grant objects...
CREATE TYPE migration_v2_lab.order_status_enum AS ENUM ('NEW', 'PAID', 'CANCELLED');

CREATE TABLE migration_v2_lab.trigger_audit_demo (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payload text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION migration_v2_lab.fn_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_set_updated_at
BEFORE UPDATE ON migration_v2_lab.trigger_audit_demo
FOR EACH ROW
EXECUTE FUNCTION migration_v2_lab.fn_set_updated_at();

CREATE OR REPLACE FUNCTION migration_v2_lab.fn_calc_fee(p_amount numeric)
RETURNS numeric
LANGUAGE sql
AS $$
    SELECT round(p_amount * 0.0125, 2);
$$;

CREATE OR REPLACE PROCEDURE migration_v2_lab.prc_tag_high_value_orders()
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE migration_v2_lab.order_fact
    SET search_text = search_text || ' [HIGH]'
    WHERE order_amount >= 2500
      AND position('[HIGH]' in search_text) = 0;
END;
$$;

CREATE VIEW migration_v2_lab.vw_high_value_orders AS
SELECT
    order_id,
    account_id,
    order_amount,
    created_at
FROM migration_v2_lab.order_fact
WHERE order_amount >= 2000;

CREATE MATERIALIZED VIEW migration_v2_lab.mv_daily_order_volume AS
SELECT
    date(created_at) AS order_date,
    count(*) AS order_count,
    sum(order_amount) AS total_amount
FROM migration_v2_lab.order_fact
GROUP BY date(created_at);

CREATE TABLE migration_v2_lab.partitioned_events (
    event_id bigint GENERATED ALWAYS AS IDENTITY,
    event_date date NOT NULL,
    event_payload text NOT NULL,
    PRIMARY KEY (event_id, event_date)
) PARTITION BY RANGE (event_date);

CREATE TABLE migration_v2_lab.partitioned_events_2025
PARTITION OF migration_v2_lab.partitioned_events
FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

CREATE TABLE migration_v2_lab.partitioned_events_2026
PARTITION OF migration_v2_lab.partitioned_events
FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

INSERT INTO migration_v2_lab.partitioned_events (event_date, event_payload)
SELECT
    date '2025-01-01' + (gs % 700),
    md5(gs::text)
FROM generate_series(1, 100000) AS gs;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'migration_v2_reader') THEN
        CREATE ROLE migration_v2_reader LOGIN;
    END IF;
END;
$$;

GRANT USAGE ON SCHEMA migration_v2_lab TO migration_v2_reader;
GRANT SELECT ON migration_v2_lab.order_fact TO migration_v2_reader;
GRANT SELECT ON migration_v2_lab.vw_high_value_orders TO migration_v2_reader;

\echo [V2 seed] Running selective ANALYZE (keeping intended stale/bloat signals)...
ANALYZE migration_v2_lab.customer_staging_no_pk;
ANALYZE migration_v2_lab.parent_accounts;
ANALYZE migration_v2_lab.child_events;
ANALYZE migration_v2_lab.sales_catalog;
ANALYZE migration_v2_lab."QuotedOrders";
ANALYZE migration_v2_lab.customer_contact_compat;
ANALYZE migration_v2_lab.amount_mapping_risk;
ANALYZE migration_v2_lab.order_fact;
ANALYZE migration_v2_lab.partitioned_events;
ANALYZE migration_v2_lab.trigger_audit_demo;

-- Intentional gaps:
-- - no index on child_events(account_id)
-- - no index on order_fact(filter_key)
-- - no functional index on lower(order_fact.search_text)
-- - stale_stats_table left unanalyzed with autovacuum disabled
-- - bloat_pressure_table left with dead tuples and autovacuum disabled

\echo [V2 seed] Seed complete.




-- SAMPLE_OUTPUT_BEGIN
-- Sample output captured from database: pgbench_test
-- Capture run directory: /tmp/pgbench_full_refresh_clean_20260218_194330
--
-- Pager usage is off.
-- [V2 seed] Recreating migration_v2_lab schema...
-- psql:27_migration_validation/05_seed_v2_test_issues.sql:18: NOTICE:  drop cascades to 19 other objects
-- DETAIL:  drop cascades to table migration_v2_lab.issue_manifest
-- drop cascades to table migration_v2_lab.customer_staging_no_pk
-- drop cascades to table migration_v2_lab.parent_accounts
-- drop cascades to table migration_v2_lab.child_events
-- drop cascades to table migration_v2_lab.sales_catalog
-- drop cascades to table migration_v2_lab.quoted_orders
-- drop cascades to table migration_v2_lab.stale_stats_table
-- drop cascades to table migration_v2_lab.bloat_pressure_table
-- drop cascades to table migration_v2_lab.customer_contact_compat
-- drop cascades to table migration_v2_lab.amount_mapping_risk
-- drop cascades to table migration_v2_lab.order_fact
-- drop cascades to type migration_v2_lab.order_status_enum
-- drop cascades to table migration_v2_lab.trigger_audit_demo
-- drop cascades to function migration_v2_lab.fn_set_updated_at()
-- drop cascades to function migration_v2_lab.fn_calc_fee(numeric)
-- drop cascades to function migration_v2_lab.prc_tag_high_value_orders()
-- drop cascades to view migration_v2_lab.vw_high_value_orders
-- drop cascades to materialized view migration_v2_lab.mv_daily_order_volume
-- drop cascades to table migration_v2_lab.partitioned_events
-- DROP SCHEMA
-- CREATE SCHEMA
-- CREATE TABLE
-- INSERT 0 11
-- [V2 seed] Creating table without PK...
-- CREATE TABLE
-- INSERT 0 60000
-- [V2 seed] Creating orphan sequence...
-- CREATE SEQUENCE
--  nextval 
-- ---------
--        1
--        2
--        3
--        4
--        5
--        6
--        7
--        8
--        9
--       10
--       11
--       12
--       13
--       14
--       15
--       16
--       17
--       18
--       19
--       20
--       21
--       22
--       23
--       24
--       25
-- (25 rows)
-- 
-- [V2 seed] Creating parent-child tables with FK missing index...
-- CREATE TABLE
-- CREATE TABLE
-- INSERT 0 50000
-- INSERT 0 250000
-- [V2 seed] Creating duplicate indexes...
-- CREATE TABLE
-- INSERT 0 120000
-- CREATE INDEX
-- CREATE INDEX
-- [V2 seed] Creating uppercase object name...
-- CREATE TABLE
-- INSERT 0 5000
-- [V2 seed] Creating stale stats table...
-- CREATE TABLE
-- ALTER TABLE
-- INSERT 0 180000
-- [V2 seed] Creating bloat pressure table...
-- CREATE TABLE
-- ALTER TABLE
-- INSERT 0 90000
-- DELETE 48000
-- [V2 seed] Creating empty-string semantic mismatch dataset...
-- CREATE TABLE
-- INSERT 0 90000
-- [V2 seed] Creating numeric mapping risk dataset...
-- CREATE TABLE
-- INSERT 0 120000
-- [V2 seed] Creating join/filter and search performance candidates...
-- CREATE TABLE
-- INSERT 0 300000
-- [V2 seed] Creating view/mview/function/procedure/trigger/partition/type/grant objects...
-- CREATE TYPE
-- CREATE TABLE
-- CREATE FUNCTION
-- CREATE TRIGGER
-- CREATE FUNCTION
-- CREATE PROCEDURE
-- CREATE VIEW
-- SELECT 1
-- CREATE TABLE
-- CREATE TABLE
-- CREATE TABLE
-- INSERT 0 100000
-- DO
-- GRANT
-- GRANT
-- GRANT
-- [V2 seed] Running selective ANALYZE (keeping intended stale/bloat signals)...
-- ANALYZE
-- ANALYZE
-- ANALYZE
-- ANALYZE
-- ANALYZE
-- ANALYZE
-- ANALYZE
-- ANALYZE
-- ANALYZE
-- ANALYZE
-- [V2 seed] Seed complete.
-- SAMPLE_OUTPUT_END
