/*
Purpose: Correlate slow-query logging threshold with pg_stat_statements hotspots.
Area: Logging and Error Signatures
Usage: Requires pg_stat_statements. Helps decide whether logging threshold is missing key queries.
*/
SELECT CASE
           WHEN EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_stat_statements') THEN 1
           ELSE 0
       END AS has_pgss
\gset

\if :has_pgss
WITH cfg AS (
    SELECT
        current_setting('log_min_duration_statement') AS raw_setting,
        CASE
            WHEN current_setting('log_min_duration_statement') ~ '^-?[0-9]+$'
                THEN current_setting('log_min_duration_statement')::numeric
            ELSE NULL::numeric
        END AS threshold_ms
),
ranked AS (
    SELECT
        queryid,
        calls,
        total_exec_time,
        mean_exec_time,
        stddev_exec_time,
        temp_blks_written,
        shared_blks_read,
        left(query, 200) AS query_snippet
    FROM pg_stat_statements
    ORDER BY total_exec_time DESC
    LIMIT 50
)
SELECT
    r.queryid,
    r.calls,
    round(r.total_exec_time::numeric, 2) AS total_exec_time_ms,
    round(r.mean_exec_time::numeric, 2) AS mean_exec_time_ms,
    round(r.stddev_exec_time::numeric, 2) AS stddev_exec_time_ms,
    r.temp_blks_written,
    r.shared_blks_read,
    c.raw_setting AS log_min_duration_statement,
    CASE
        WHEN c.threshold_ms = -1 THEN 'NOT_LOGGED'
        WHEN c.threshold_ms = 0 THEN 'LOGGED_ALWAYS'
        WHEN r.mean_exec_time >= c.threshold_ms THEN 'LIKELY_LOGGED'
        ELSE 'LIKELY_NOT_LOGGED'
    END AS log_visibility,
    r.query_snippet
FROM ranked r
CROSS JOIN cfg c
ORDER BY r.total_exec_time DESC;
\else
SELECT
    'pg_stat_statements extension is not installed. Run: CREATE EXTENSION pg_stat_statements;'::text AS guidance;
\endif


-- SAMPLE_OUTPUT_BEGIN
-- Sample output captured from database: pgbench_test
-- Capture run directory: /tmp/pgbench_new_areas_20260219_refresh
--
--        queryid        |  calls  | total_exec_time_ms | mean_exec_time_ms | stddev_exec_time_ms | temp_blks_written | shared_blks_read | log_min_duration_statement | log_visibility |                                                                           query_snippet                                                                           
-- ----------------------+---------+--------------------+-------------------+---------------------+-------------------+------------------+----------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------
--   1144016440436625022 | 7727669 |        21709355.83 |              2.81 |               76.71 |                 0 |         15462165 | -1                         | NOT_LOGGED     | UPDATE pgbench_accounts SET abalance = abalance + $1 WHERE aid = $2
--  -5371882943115234533 | 7727470 |          472472.42 |              0.06 |                1.74 |                 0 |             1732 | -1                         | NOT_LOGGED     | UPDATE pgbench_branches SET bbalance = bbalance + $1 WHERE bid = $2
--   -305747636952590102 | 7727491 |          242694.90 |              0.03 |                0.53 |                 0 |             1998 | -1                         | NOT_LOGGED     | UPDATE pgbench_tellers SET tbalance = tbalance + $1 WHERE tid = $2
--   3387776431457662738 | 7727449 |          123278.39 |              0.02 |                2.08 |                 0 |            22619 | -1                         | NOT_LOGGED     | INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP)
--  -1078345578982625442 | 7727506 |           48400.31 |              0.01 |                0.04 |                 0 |               98 | -1                         | NOT_LOGGED     | SELECT abalance FROM pgbench_accounts WHERE aid = $1
--   -214248046822219685 |       2 |           37841.83 |          18920.92 |             1072.63 |             15408 |          1313283 | -1                         | NOT_LOGGED     | DO $$                                                                                                                                                            +
--                       |         |                    |                   |                     |                   |                  |                            |                | DECLARE                                                                                                                                                          +
--                       |         |                    |                   |                     |                   |                  |                            |                |     v_schema text;                                                                                                                                               +
--                       |         |                    |                   |                     |                   |                  |                            |                |     v_table text;                                                                                                                                                +
--                       |         |                    |                   |                     |                   |                  |                            |                |     v_history_years int;                                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     v_target_gb numeric;                                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     v_payload_bytes int;                                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     v_batch_rows int;                                                                                                                                            +
--                       |         |                    |                   |                     |                   |                  |                            |                |     v_target_bytes bigint;                                                                                                                                       +
--                       |         |                    |                   |                     |                   |                  |                            |                |     v_start_date date;                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |   
--  -6127080060642381402 |      36 |           36092.24 |           1002.56 |               74.11 |             15408 |                4 | -1                         | NOT_LOGGED     | INSERT INTO partition_lab.fact_events_10y_unpartitioned (event_date, account_id, amount, payload)                                                                +
--                       |         |                    |                   |                     |                   |                  |                            |                |             SELECT                                                                                                                                               +
--                       |         |                    |                   |                     |                   |                  |                            |                |                 ($1::date + ((gs - $2) % $3))::date AS event_date,                                                                                               +
--                       |         |                    |                   |                     |                   |                  |                            |                |                 
--   3481893718825960883 |    7109 |           20055.74 |              2.82 |              117.82 |                 0 |               97 | -1                         | NOT_LOGGED     | SELECT $1 AS chart_name, pg_catalog.row_to_json(t) AS chart_data                                                                                                 +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM (SELECT                                                                                                                                                     +
--                       |         |                    |                   |                     |                   |                  |                            |                |    (SELECT count(*) FROM pg_catalog.pg_stat_activity WHERE datname = (SELECT datname FROM pg_catalog.pg_database WHERE oid
--  -8275299279783089467 |       6 |            6922.60 |           1153.77 |               19.76 |              9640 |               17 | -1                         | NOT_LOGGED     | CREATE INDEX IF NOT EXISTS idx_v2_order_fact_search_lower                                                                                                        +
--                       |         |                    |                   |                     |                   |                  |                            |                |     ON migration_v2_lab.order_fact (lower(search_text))
--  -6652883949691502391 |       6 |            6777.13 |           1129.52 |               81.19 |              2568 |                6 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.child_events (account_id, event_type, amount)                                                                                       +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     ($1 + (random() * $2)::int)::bigint,                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     CASE WHEN gs % $3 = $4 THEN $5 WHEN gs % $6 = $7 THEN $8 ELSE $9 END,                                                                                        +
--                       |         |                    |                   |                     |                   |                  |                            |                |    
--    847396262454713343 |       6 |            4926.30 |            821.05 |              125.01 |              3078 |                6 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.order_fact (account_id, filter_key, search_text, order_amount)                                                                      +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     ($1 + (random() * $2)::int)::bigint,                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     ($3 + (random() * $4)::int),                                                                                                                                 +
--                       |         |                    |                   |                     |                   |                  |                            |                |     CASE WHEN gs % $5 = $6 
--  -3869797102397106429 |       6 |            4568.00 |            761.33 |               33.40 |                 0 |                6 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.bloat_pressure_table (payload)                                                                                                      +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT repeat(md5(gs::text), $1)                                                                                                                                 +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($2, $3) AS gs
--  -5065162101678021495 |       9 |            4116.56 |            457.40 |              217.63 |              1848 |                9 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.stale_stats_table (payload)                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT md5(random()::text) || md5((random() * $1)::text)                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($2, $3)
--   1459853053728673055 |      12 |            2827.29 |            235.61 |               73.25 |                 0 |                4 | -1                         | NOT_LOGGED     | ANALYZE migration_v2_lab.order_fact
--   2285531965341755341 |       6 |            2721.26 |            453.54 |              108.07 |                 0 |             1209 | -1                         | NOT_LOGGED     | UPDATE migration_v2_lab.amount_mapping_risk                                                                                                                      +
--                       |         |                    |                   |                     |                   |                  |                            |                | SET                                                                                                                                                              +
--                       |         |                    |                   |                     |                   |                  |                            |                |     target_int4_model = CASE                                                                                                                                     +
--                       |         |                    |                   |                     |                   |                  |                            |                |         WHEN abs(source_numeric) <= $1 THEN source_numeric::int                                                                                                  +
--                       |         |                    |                   |                     |                   |                  |                            |                |         ELSE target_int4_model                                                                                                                                   +
--                       |         |                    |                   |                     |                   |                  |                            |                |     END,                                                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     target_bigint_m
--    215870004070435986 |      12 |            2700.87 |            225.07 |                4.46 |                 0 |               35 | -1                         | NOT_LOGGED     | ANALYZE migration_v2_lab.partitioned_events
--  -1479418139676470911 |       6 |            2322.90 |            387.15 |                6.22 |                 0 |                0 | -1                         | NOT_LOGGED     | CREATE INDEX idx_v2_sales_ref_b ON migration_v2_lab.sales_catalog (item_ref)
--   4361856503355632769 |       6 |            2305.64 |            384.27 |               10.52 |                 0 |                0 | -1                         | NOT_LOGGED     | CREATE INDEX idx_v2_sales_ref_a ON migration_v2_lab.sales_catalog (item_ref)
--   7127220720807722591 |       4 |            2175.88 |            543.97 |               43.37 |               824 |                4 | -1                         | NOT_LOGGED     | INSERT INTO migration_v1_lab.child_transactions (account_id, amount)                                                                                             +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     ($1 + (random() * $2)::int)::bigint,                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     round((random() * $3)::numeric, $4)                                                                                                                          +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($5, $6)
--   3689806360888379158 | 1860000 |            1823.68 |              0.00 |                0.01 |                 0 |                0 | -1                         | NOT_LOGGED     | SELECT $2 FROM ONLY "migration_v2_lab"."parent_accounts" x WHERE "account_id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x
--   4667898782383165389 |       6 |            1701.86 |            283.64 |               36.85 |              1236 |                6 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.sales_catalog (item_ref, item_type, price)                                                                                          +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     $1 || gs,                                                                                                                                                    +
--                       |         |                    |                   |                     |                   |                  |                            |                |     CASE WHEN gs % $2 = $3 THEN $4 WHEN gs % $5 = $6 THEN $7 WHEN gs % $8 = $9 THEN $10 WHEN gs % $11 = $12
--    450201137788272562 |       1 |            1674.50 |           1674.50 |                0.00 |                 0 |            29989 | -1                         | NOT_LOGGED     | ANALYZE
--   7127220720807722591 |       3 |            1649.31 |            549.77 |               67.33 |               618 |                3 | -1                         | NOT_LOGGED     | INSERT INTO migration_v1_lab.child_transactions (account_id, amount)                                                                                             +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     ($1 + (random() * $2)::int)::bigint,                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     round((random() * $3)::numeric, $4)                                                                                                                          +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($5, $6)
--   7127220720807722591 |       3 |            1636.26 |            545.42 |               19.71 |               618 |                3 | -1                         | NOT_LOGGED     | INSERT INTO migration_v1_lab.child_transactions (account_id, amount)                                                                                             +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     ($1 + (random() * $2)::int)::bigint,                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     round((random() * $3)::numeric, $4)                                                                                                                          +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($5, $6)
--  -3514466126412688923 |      29 |            1589.43 |             54.81 |               19.19 |                 0 |                4 | -1                         | NOT_LOGGED     | SELECT COALESCE(queryid::text, $1) AS queryid,                                                                                                                   +
--                       |         |                    |                   |                     |                   |                  |                            |                |                    calls::numeric AS calls,                                                                                                                      +
--                       |         |                    |                   |                     |                   |                  |                            |                |                    total_exec_time::numeric AS total_exec_ms,                                                                                                    +
--                       |         |                    |                   |                     |                   |                  |                            |                |                    mean_exec_time::numeric AS a
--  -2413577522733086265 |       3 |            1584.69 |            528.23 |              423.19 |                 0 |          1883160 | -1                         | NOT_LOGGED     | SELECT min(event_date)::timestamptz, max(event_date)::timestamptz, count(*)::bigint FROM partition_lab.fact_events_10y_unpartitioned WHERE event_date IS NOT NULL
--  -5938169015537755073 |       6 |            1461.03 |            243.51 |               35.48 |                 0 |               12 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.partitioned_events (event_date, event_payload)                                                                                      +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     date $1 + (gs % $2),                                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |     md5(gs::text)                                                                                                                                                +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($3, $4) AS gs
--  -2522370506372832129 |      12 |            1422.94 |            118.58 |                4.86 |                 0 |             1487 | -1                         | NOT_LOGGED     | ANALYZE migration_v2_lab.customer_contact_compat
--   1579180460630060410 |       6 |            1261.81 |            210.30 |               33.75 |              1236 |                6 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.amount_mapping_risk (source_numeric, target_int4_model)                                                                             +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     CASE                                                                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                |         WHEN gs % $1 = $2 THEN $3 + gs                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |         WHEN gs % $4 = $5 THEN $6 - gs                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |         ELSE gs::nume
--  -7376821209867977575 |      12 |            1197.60 |             99.80 |                2.61 |                 0 |                3 | -1                         | NOT_LOGGED     | ANALYZE migration_v2_lab.sales_catalog
--  -4598960938853719316 |       4 |            1100.35 |            275.09 |               12.22 |                 0 |                4 | -1                         | NOT_LOGGED     | INSERT INTO migration_v1_lab.dml_bloat_table (payload)                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT repeat(md5(gs::text), $1)                                                                                                                                 +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($2, $3) AS gs
--   7707833258187676424 |       2 |            1079.22 |            539.61 |              539.51 |                 0 |                6 | -1                         | NOT_LOGGED     | DROP TABLE IF EXISTS partition_lab.fact_events_10y_unpartitioned
--   1330686554379899739 |       6 |            1045.95 |            174.32 |               29.62 |                 0 |                6 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.customer_contact_compat (email, phone, comments)                                                                                    +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT                                                                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                |     CASE WHEN gs % $1 = $2 THEN $3 ELSE $4 || gs || $5 END,                                                                                                      +
--                       |         |                    |                   |                     |                   |                  |                            |                |     CASE WHEN gs % $6 = $7 THEN $8 ELSE $9 || lpad((gs 
--   1021157187189676460 |      12 |            1026.37 |             85.53 |                2.26 |                 0 |              929 | -1                         | NOT_LOGGED     | ANALYZE migration_v2_lab.customer_staging_no_pk
--   3911214664636020243 |       6 |            1002.53 |            167.09 |               26.54 |                 0 |             1468 | -1                         | NOT_LOGGED     | UPDATE migration_v2_lab.customer_contact_compat                                                                                                                  +
--                       |         |                    |                   |                     |                   |                  |                            |                | SET                                                                                                                                                              +
--                       |         |                    |                   |                     |                   |                  |                            |                |     email = NULLIF(email, $1),                                                                                                                                   +
--                       |         |                    |                   |                     |                   |                  |                            |                |     phone = NULLIF(phone, $2),                                                                                                                                   +
--                       |         |                    |                   |                     |                   |                  |                            |                |     comments = NULLIF(comments, $3)                                                                                                                              +
--                       |         |                    |                   |                     |                   |                  |                            |                | WHERE email = $4 OR phone = $5 OR comments = $6
--  -1900060566350483813 |      12 |             934.35 |             77.86 |                1.82 |                 0 |             1335 | -1                         | NOT_LOGGED     | ANALYZE migration_v2_lab.parent_accounts
--   1901987179462105607 |      67 |             896.43 |             13.38 |                6.82 |                 0 |               44 | -1                         | NOT_LOGGED     | SELECT datname,                                                                                                                                                  +
--                       |         |                    |                   |                     |                   |                  |                            |                |        datallowconn,                                                                                                                                             +
--                       |         |                    |                   |                     |                   |                  |                            |                |        datconnlimit,                                                                                                                                             +
--                       |         |                    |                   |                     |                   |                  |                            |                |        pg_encoding_to_char(encoding) AS encoding,                                                                                                                +
--                       |         |                    |                   |                     |                   |                  |                            |                |        datcollate,                                                                                                                                               +
--                       |         |                    |                   |                     |                   |                  |                            |                |        datctype,                                                                                                                                                 +
--                       |         |                    |                   |                     |                   |                  |                            |                |        pg_size_pretty(pg_database_size(datname)) AS data
--   6097083398544187049 | 7727416 |             857.36 |              0.00 |                0.00 |                 0 |                0 | -1                         | NOT_LOGGED     | END
--   4854991825702068830 | 7727688 |             844.52 |              0.00 |                0.00 |                 0 |                0 | -1                         | NOT_LOGGED     | BEGIN
--  -4598960938853719316 |       3 |             835.59 |            278.53 |               12.20 |                 0 |                3 | -1                         | NOT_LOGGED     | INSERT INTO migration_v1_lab.dml_bloat_table (payload)                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT repeat(md5(gs::text), $1)                                                                                                                                 +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($2, $3) AS gs
--  -4598960938853719316 |       3 |             805.66 |            268.55 |                9.76 |                 0 |                3 | -1                         | NOT_LOGGED     | INSERT INTO migration_v1_lab.dml_bloat_table (payload)                                                                                                           +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT repeat(md5(gs::text), $1)                                                                                                                                 +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($2, $3) AS gs
--  -5398677000037045473 |       1 |             802.50 |            802.50 |                0.00 |                 0 |            53105 | -1                         | NOT_LOGGED     | CREATE DATABASE script_validation_20260218_172749 TEMPLATE perf_test
--  -5065162101678021495 |       4 |             786.32 |            196.58 |               16.57 |                 0 |                4 | -1                         | NOT_LOGGED     | INSERT INTO migration_v1_lab.stale_stats_table (payload)                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT md5(random()::text) || md5((random() * $1)::text)                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($2, $3)
--    921579968067292190 |       6 |             722.58 |            120.43 |                3.14 |                 0 |             7074 | -1                         | NOT_LOGGED     | ANALYZE migration_v2_lab.stale_stats_table
--  -4122962008160556687 |       6 |             662.41 |            110.40 |                1.74 |                 0 |                2 | -1                         | NOT_LOGGED     | ANALYZE migration_v1_lab.stale_stats_table
--  -5065162101678021495 |       3 |             549.84 |            183.28 |                1.70 |                 0 |                3 | -1                         | NOT_LOGGED     | INSERT INTO migration_v1_lab.stale_stats_table (payload)                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT md5(random()::text) || md5((random() * $1)::text)                                                                                                         +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($2, $3)
--  -6785520009338350043 |       4 |             508.53 |            127.13 |                1.37 |                 0 |                0 | -1                         | NOT_LOGGED     | CREATE INDEX idx_product_sku_a ON migration_v1_lab.product_catalog (sku)
--   5250747760378150803 |       4 |             506.31 |            126.58 |                1.57 |                 0 |                0 | -1                         | NOT_LOGGED     | CREATE INDEX idx_product_sku_b ON migration_v1_lab.product_catalog (sku)
--  -2039736649399175093 |      31 |             470.57 |             15.18 |               13.55 |                 0 |                0 | -1                         | NOT_LOGGED     | SELECT datname,                                                                                                                                                  +
--                       |         |                    |                   |                     |                   |                  |                            |                |        pg_size_pretty(pg_database_size(datname)) AS database_size,                                                                                               +
--                       |         |                    |                   |                     |                   |                  |                            |                |        pg_database_size(datname) AS database_bytes                                                                                                               +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM pg_database                                                                                                                                                 +
--                       |         |                    |                   |                     |                   |                  |                            |                | ORDER BY database_bytes DESC
--   9120805628915790401 |       9 |             464.84 |             51.65 |               33.42 |                 0 |                9 | -1                         | NOT_LOGGED     | INSERT INTO migration_v2_lab.parent_accounts (account_id, account_name)                                                                                          +
--                       |         |                    |                   |                     |                   |                  |                            |                | SELECT gs, $1 || gs                                                                                                                                              +
--                       |         |                    |                   |                     |                   |                  |                            |                | FROM generate_series($2, $3) AS gs
-- (50 rows)
-- 
-- SAMPLE_OUTPUT_END
