/*
Purpose: Profile largest system catalogs to understand metadata footprint.
Area: Internals Deep Dive
Usage: Run in each critical database.
*/
SELECT
    n.nspname AS schema_name,
    c.relname AS catalog_name,
    c.relkind,
    pg_total_relation_size(c.oid) AS total_bytes,
    pg_size_pretty(pg_total_relation_size(c.oid)) AS total_pretty
FROM pg_class c
JOIN pg_namespace n
    ON n.oid = c.relnamespace
WHERE n.nspname IN ('pg_catalog', 'information_schema')
ORDER BY total_bytes DESC;


/* SAMPLE_OUTPUT_BEGIN
Sample output (captured from local validation run; values may vary by environment).

    schema_name     |                  catalog_name                  | relkind | total_bytes | total_pretty 
--------------------+------------------------------------------------+---------+-------------+--------------
 pg_catalog         | pg_proc                                        | r       |     1302528 | 1272 kB
 pg_catalog         | pg_attribute                                   | r       |     1073152 | 1048 kB
 pg_catalog         | pg_rewrite                                     | r       |      778240 | 760 kB
 pg_catalog         | pg_description                                 | r       |      638976 | 624 kB
 pg_catalog         | pg_statistic                                   | r       |      483328 | 472 kB
 pg_catalog         | pg_depend                                      | r       |      450560 | 440 kB
 pg_catalog         | pg_collation                                   | r       |      360448 | 352 kB
 pg_catalog         | pg_constraint                                  | r       |      319488 | 312 kB
 pg_catalog         | pg_type                                        | r       |      286720 | 280 kB
 pg_catalog         | pg_class                                       | r       |      286720 | 280 kB
 pg_catalog         | pg_proc_proname_args_nsp_index                 | i       |      270336 | 264 kB
 pg_catalog         | pg_operator                                    | r       |      237568 | 232 kB
 pg_catalog         | pg_amop                                        | r       |      229376 | 224 kB
 pg_catalog         | pg_description_o_c_o_index                     | i       |      221184 | 216 kB
 pg_catalog         | pg_attribute_relid_attnam_index                | i       |      196608 | 192 kB
 pg_catalog         | pg_amproc                                      | r       |      147456 | 144 kB
 pg_catalog         | pg_depend_depender_index                       | i       |      147456 | 144 kB
 pg_catalog         | pg_attribute_relid_attnum_index                | i       |      131072 | 128 kB
 pg_catalog         | pg_index                                       | r       |      122880 | 120 kB
 pg_catalog         | pg_auth_members                                | r       |      106496 | 104 kB
 pg_catalog         | pg_ts_config_map                               | r       |      106496 | 104 kB
 information_schema | sql_features                                   | r       |      106496 | 104 kB
 pg_catalog         | pg_conversion                                  | r       |       98304 | 96 kB
 pg_catalog         | pg_trigger                                     | r       |       98304 | 96 kB
 pg_catalog         | pg_depend_reference_index                      | i       |       98304 | 96 kB
 pg_catalog         | pg_proc_oid_index                              | i       |       98304 | 96 kB
 pg_catalog         | pg_opclass                                     | r       |       90112 | 88 kB
 pg_catalog         | pg_collation_name_enc_nsp_index                | i       |       81920 | 80 kB
 pg_catalog         | pg_extension                                   | r       |       81920 | 80 kB
 pg_catalog         | pg_opfamily                                    | r       |       81920 | 80 kB
 pg_catalog         | pg_database                                    | r       |       81920 | 80 kB
 pg_catalog         | pg_tablespace                                  | r       |       81920 | 80 kB
 pg_catalog         | pg_namespace                                   | r       |       81920 | 80 kB
 pg_catalog         | pg_init_privs                                  | r       |       81920 | 80 kB
 pg_catalog         | pg_aggregate                                   | r       |       81920 | 80 kB
 pg_catalog         | pg_language                                    | r       |       81920 | 80 kB
 pg_catalog         | pg_attrdef                                     | r       |       81920 | 80 kB
 pg_catalog         | pg_ts_dict                                     | r       |       81920 | 80 kB
 pg_catalog         | pg_cast                                        | r       |       81920 | 80 kB
 pg_catalog         | pg_range                                       | r       |       73728 | 72 kB
 pg_catalog         | pg_ts_parser                                   | r       |       73728 | 72 kB
 pg_catalog         | pg_ts_config                                   | r       |       73728 | 72 kB
 pg_catalog         | pg_am                                          | r       |       73728 | 72 kB
 pg_catalog         | pg_authid                                      | r       |       73728 | 72 kB
 pg_catalog         | pg_ts_template                                 | r       |       73728 | 72 kB
 pg_catalog         | pg_class_relname_nsp_index                     | i       |       65536 | 64 kB
 pg_catalog         | pg_type_typname_nsp_index                      | i       |       65536 | 64 kB
 pg_catalog         | pg_shdescription                               | r       |       65536 | 64 kB
 pg_catalog         | pg_constraint_conname_nsp_index                | i       |       65536 | 64 kB
 pg_catalog         | pg_constraint_conrelid_contypid_conname_index  | i       |       57344 | 56 kB
 pg_catalog         | pg_amop_opr_fam_index                          | i       |       49152 | 48 kB
 information_schema | sql_implementation_info                        | r       |       49152 | 48 kB
 pg_catalog         | pg_collation_oid_index                         | i       |       49152 | 48 kB
 pg_catalog         | pg_operator_oprname_l_r_n_index                | i       |       49152 | 48 kB
 information_schema | sql_parts                                      | r       |       49152 | 48 kB
 information_schema | sql_sizing                                     | r       |       49152 | 48 kB
 pg_catalog         | pg_amop_fam_strat_index                        | i       |       49152 | 48 kB
 pg_catalog         | pg_amproc_fam_proc_index                       | i       |       40960 | 40 kB
 pg_catalog         | pg_amop_oid_index                              | i       |       40960 | 40 kB
 pg_catalog         | pg_ts_config_map_index                         | i       |       40960 | 40 kB
 pg_catalog         | pg_statistic_relid_att_inh_index               | i       |       40960 | 40 kB
 pg_catalog         | pg_operator_oid_index                          | i       |       40960 | 40 kB
 pg_catalog         | pg_shdepend                                    | r       |       40960 | 40 kB
 pg_catalog         | pg_statistic_ext                               | r       |       32768 | 32 kB
 pg_catalog         | pg_type_oid_index                              | i       |       32768 | 32 kB
 pg_catalog         | pg_constraint_oid_index                        | i       |       32768 | 32 kB
 pg_catalog         | pg_class_oid_index                             | i       |       32768 | 32 kB
 pg_catalog         | pg_class_tblspc_relfilenode_index              | i       |       32768 | 32 kB
 pg_catalog         | pg_publication_rel                             | r       |       32768 | 32 kB
 pg_catalog         | pg_amproc_oid_index                            | i       |       32768 | 32 kB
 pg_catalog         | pg_policy                                      | r       |       24576 | 24 kB
 pg_catalog         | pg_parameter_acl                               | r       |       24576 | 24 kB
 pg_catalog         | pg_default_acl                                 | r       |       24576 | 24 kB
 pg_catalog         | pg_enum                                        | r       |       24576 | 24 kB
 pg_catalog         | pg_subscription                                | r       |       24576 | 24 kB
 pg_catalog         | pg_user_mapping                                | r       |       24576 | 24 kB
 pg_catalog         | pg_foreign_server                              | r       |       24576 | 24 kB
 pg_catalog         | pg_foreign_data_wrapper                        | r       |       24576 | 24 kB
 pg_catalog         | pg_sequence                                    | r       |       24576 | 24 kB
 pg_catalog         | pg_event_trigger                               | r       |       24576 | 24 kB
 pg_catalog         | pg_ts_dict_oid_index                           | i       |       16384 | 16 kB
 pg_catalog         | pg_foreign_table                               | r       |       16384 | 16 kB
 pg_catalog         | pg_attrdef_adrelid_adnum_index                 | i       |       16384 | 16 kB
 pg_catalog         | pg_attrdef_oid_index                           | i       |       16384 | 16 kB
 pg_catalog         | pg_constraint_contypid_index                   | i       |       16384 | 16 kB
 pg_catalog         | pg_constraint_conparentid_index                | i       |       16384 | 16 kB
 pg_catalog         | pg_index_indrelid_index                        | i       |       16384 | 16 kB
 pg_catalog         | pg_index_indexrelid_index                      | i       |       16384 | 16 kB
 pg_catalog         | pg_opfamily_am_name_nsp_index                  | i       |       16384 | 16 kB
 pg_catalog         | pg_opfamily_oid_index                          | i       |       16384 | 16 kB
 pg_catalog         | pg_opclass_am_name_nsp_index                   | i       |       16384 | 16 kB
 pg_catalog         | pg_opclass_oid_index                           | i       |       16384 | 16 kB
 pg_catalog         | pg_am_name_index                               | i       |       16384 | 16 kB
 pg_catalog         | pg_am_oid_index                                | i       |       16384 | 16 kB
 pg_catalog         | pg_language_name_index                         | i       |       16384 | 16 kB
 pg_catalog         | pg_language_oid_index                          | i       |       16384 | 16 kB
 pg_catalog         | pg_aggregate_fnoid_index                       | i       |       16384 | 16 kB
 pg_catalog         | pg_rewrite_oid_index                           | i       |       16384 | 16 kB
 pg_catalog         | pg_rewrite_rel_rulename_index                  | i       |       16384 | 16 kB
 pg_catalog         | pg_trigger_tgconstraint_index                  | i       |       16384 | 16 kB
 pg_catalog         | pg_trigger_tgrelid_tgname_index                | i       |       16384 | 16 kB
 pg_catalog         | pg_trigger_oid_index                           | i       |       16384 | 16 kB
 pg_catalog         | pg_cast_oid_index                              | i       |       16384 | 16 kB
 pg_catalog         | pg_cast_source_target_index                    | i       |       16384 | 16 kB
 pg_catalog         | pg_namespace_nspname_index                     | i       |       16384 | 16 kB
 pg_catalog         | pg_namespace_oid_index                         | i       |       16384 | 16 kB
 pg_catalog         | pg_conversion_default_index                    | i       |       16384 | 16 kB
 pg_catalog         | pg_conversion_name_nsp_index                   | i       |       16384 | 16 kB
 pg_catalog         | pg_conversion_oid_index                        | i       |       16384 | 16 kB
 pg_catalog         | pg_database_datname_index                      | i       |       16384 | 16 kB
 pg_catalog         | pg_database_oid_index                          | i       |       16384 | 16 kB
 pg_catalog         | pg_tablespace_oid_index                        | i       |       16384 | 16 kB
 pg_catalog         | pg_tablespace_spcname_index                    | i       |       16384 | 16 kB
 pg_catalog         | pg_authid_rolname_index                        | i       |       16384 | 16 kB
 pg_catalog         | pg_authid_oid_index                            | i       |       16384 | 16 kB
 pg_catalog         | pg_auth_members_oid_index                      | i       |       16384 | 16 kB
 pg_catalog         | pg_auth_members_role_member_index              | i       |       16384 | 16 kB
 pg_catalog         | pg_auth_members_member_role_index              | i       |       16384 | 16 kB
 pg_catalog         | pg_auth_members_grantor_index                  | i       |       16384 | 16 kB
 pg_catalog         | pg_shdepend_depender_index                     | i       |       16384 | 16 kB
 pg_catalog         | pg_shdepend_reference_index                    | i       |       16384 | 16 kB
 pg_catalog         | pg_shdescription_o_c_index                     | i       |       16384 | 16 kB
 pg_catalog         | pg_ts_config_cfgname_index                     | i       |       16384 | 16 kB
 pg_catalog         | pg_ts_config_oid_index                         | i       |       16384 | 16 kB
 pg_catalog         | pg_ts_dict_dictname_index                      | i       |       16384 | 16 kB
 pg_catalog         | pg_ts_parser_prsname_index                     | i       |       16384 | 16 kB
 pg_catalog         | pg_ts_parser_oid_index                         | i       |       16384 | 16 kB
 pg_catalog         | pg_ts_template_tmplname_index                  | i       |       16384 | 16 kB
 pg_catalog         | pg_ts_template_oid_index                       | i       |       16384 | 16 kB
 pg_catalog         | pg_extension_oid_index                         | i       |       16384 | 16 kB
 pg_catalog         | pg_extension_name_index                        | i       |       16384 | 16 kB
 pg_catalog         | pg_init_privs_o_c_o_index                      | i       |       16384 | 16 kB
 pg_catalog         | pg_range_rngtypid_index                        | i       |       16384 | 16 kB
 pg_catalog         | pg_range_rngmultitypid_index                   | i       |       16384 | 16 kB
 pg_catalog         | pg_sequence_seqrelid_index                     | i       |       16384 | 16 kB
 pg_catalog         | pg_statistic_ext_data                          | r       |       16384 | 16 kB
 pg_catalog         | pg_inherits                                    | r       |       16384 | 16 kB
 pg_catalog         | pg_db_role_setting                             | r       |       16384 | 16 kB
 pg_catalog         | pg_replication_origin                          | r       |       16384 | 16 kB
 pg_catalog         | pg_seclabel                                    | r       |       16384 | 16 kB
 pg_catalog         | pg_shseclabel                                  | r       |       16384 | 16 kB
 pg_catalog         | pg_partitioned_table                           | r       |       16384 | 16 kB
 pg_catalog         | pg_transform                                   | r       |       16384 | 16 kB
 pg_catalog         | pg_publication                                 | r       |       16384 | 16 kB
 pg_catalog         | pg_publication_namespace                       | r       |       16384 | 16 kB
 pg_catalog         | pg_db_role_setting_databaseid_rol_index        | i       |        8192 | 8192 bytes
 pg_catalog         | pg_enum_typid_sortorder_index                  | i       |        8192 | 8192 bytes
 pg_catalog         | pg_enum_typid_label_index                      | i       |        8192 | 8192 bytes
 pg_catalog         | pg_enum_oid_index                              | i       |        8192 | 8192 bytes
 pg_catalog         | pg_event_trigger_oid_index                     | i       |        8192 | 8192 bytes
 pg_catalog         | pg_subscription_rel_srrelid_srsubid_index      | i       |        8192 | 8192 bytes
 pg_catalog         | pg_event_trigger_evtname_index                 | i       |        8192 | 8192 bytes
 pg_catalog         | pg_statistic_ext_data_stxoid_inh_index         | i       |        8192 | 8192 bytes
 pg_catalog         | pg_subscription_oid_index                      | i       |        8192 | 8192 bytes
 pg_catalog         | pg_publication_rel_prpubid_index               | i       |        8192 | 8192 bytes
 pg_catalog         | pg_statistic_ext_relid_index                   | i       |        8192 | 8192 bytes
 pg_catalog         | pg_statistic_ext_name_index                    | i       |        8192 | 8192 bytes
 pg_catalog         | pg_publication_rel_prrelid_prpubid_index       | i       |        8192 | 8192 bytes
 pg_catalog         | pg_inherits_parent_index                       | i       |        8192 | 8192 bytes
 pg_catalog         | pg_inherits_relid_seqno_index                  | i       |        8192 | 8192 bytes
 pg_catalog         | pg_statistic_ext_oid_index                     | i       |        8192 | 8192 bytes
 pg_catalog         | pg_publication_rel_oid_index                   | i       |        8192 | 8192 bytes
 pg_catalog         | pg_largeobject_loid_pn_index                   | i       |        8192 | 8192 bytes
 pg_catalog         | pg_publication_namespace_pnnspid_pnpubid_index | i       |        8192 | 8192 bytes
 pg_catalog         | pg_publication_namespace_oid_index             | i       |        8192 | 8192 bytes
 pg_catalog         | pg_largeobject_metadata_oid_index              | i       |        8192 | 8192 bytes
 pg_catalog         | pg_subscription_rel                            | r       |        8192 | 8192 bytes
 pg_catalog         | pg_publication_pubname_index                   | i       |        8192 | 8192 bytes
 pg_catalog         | pg_publication_oid_index                       | i       |        8192 | 8192 bytes
 pg_catalog         | pg_largeobject_metadata                        | r       |        8192 | 8192 bytes
 pg_catalog         | pg_transform_type_lang_index                   | i       |        8192 | 8192 bytes
 pg_catalog         | pg_transform_oid_index                         | i       |        8192 | 8192 bytes
 pg_catalog         | pg_partitioned_table_partrelid_index           | i       |        8192 | 8192 bytes
 pg_catalog         | pg_parameter_acl_oid_index                     | i       |        8192 | 8192 bytes
 pg_catalog         | pg_parameter_acl_parname_index                 | i       |        8192 | 8192 bytes
 pg_catalog         | pg_shseclabel_object_index                     | i       |        8192 | 8192 bytes
 pg_catalog         | pg_seclabel_object_index                       | i       |        8192 | 8192 bytes
 pg_catalog         | pg_default_acl_oid_index                       | i       |        8192 | 8192 bytes
 pg_catalog         | pg_default_acl_role_nsp_obj_index              | i       |        8192 | 8192 bytes
 pg_catalog         | pg_replication_origin_roname_index             | i       |        8192 | 8192 bytes
 pg_catalog         | pg_replication_origin_roiident_index           | i       |        8192 | 8192 bytes
 pg_catalog         | pg_policy_polrelid_polname_index               | i       |        8192 | 8192 bytes
 pg_catalog         | pg_subscription_subname_index                  | i       |        8192 | 8192 bytes
 pg_catalog         | pg_policy_oid_index                            | i       |        8192 | 8192 bytes
 pg_catalog         | pg_foreign_table_relid_index                   | i       |        8192 | 8192 bytes
 pg_catalog         | pg_user_mapping_user_server_index              | i       |        8192 | 8192 bytes
 pg_catalog         | pg_user_mapping_oid_index                      | i       |        8192 | 8192 bytes
 pg_catalog         | pg_foreign_server_name_index                   | i       |        8192 | 8192 bytes
 pg_catalog         | pg_largeobject                                 | r       |        8192 | 8192 bytes
 pg_catalog         | pg_foreign_server_oid_index                    | i       |        8192 | 8192 bytes
 pg_catalog         | pg_foreign_data_wrapper_name_index             | i       |        8192 | 8192 bytes
 pg_catalog         | pg_foreign_data_wrapper_oid_index              | i       |        8192 | 8192 bytes
 pg_catalog         | pg_available_extensions                        | v       |           0 | 0 bytes
 pg_catalog         | pg_available_extension_versions                | v       |           0 | 0 bytes
 pg_catalog         | pg_prepared_xacts                              | v       |           0 | 0 bytes
 pg_catalog         | pg_prepared_statements                         | v       |           0 | 0 bytes
 pg_catalog         | pg_seclabels                                   | v       |           0 | 0 bytes
 pg_catalog         | pg_timezone_abbrevs                            | v       |           0 | 0 bytes
 pg_catalog         | pg_timezone_names                              | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_all_tables                             | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_xact_all_tables                        | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_xact_user_tables                       | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_sys_tables                             | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_xact_sys_tables                        | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_user_tables                            | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_all_tables                           | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_sys_tables                           | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_user_tables                          | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_all_indexes                            | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_sys_indexes                            | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_user_indexes                           | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_all_indexes                          | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_sys_indexes                          | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_user_indexes                         | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_all_sequences                        | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_replication                            | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_slru                                   | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_wal_receiver                           | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_recovery_prefetch                      | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_subscription                           | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_ssl                                    | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_gssapi                                 | v       |           0 | 0 bytes
 pg_catalog         | pg_replication_slots                           | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_replication_slots                      | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_database                               | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_database_conflicts                     | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_user_functions                         | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_xact_user_functions                    | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_archiver                               | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_bgwriter                               | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_checkpointer                           | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_io                                     | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_wal                                    | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_progress_analyze                       | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_progress_vacuum                        | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_progress_cluster                       | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_progress_create_index                  | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_progress_basebackup                    | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_progress_copy                          | v       |           0 | 0 bytes
 pg_catalog         | pg_user_mappings                               | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_subscription_stats                     | v       |           0 | 0 bytes
 pg_catalog         | pg_wait_events                                 | v       |           0 | 0 bytes
 information_schema | information_schema_catalog_name                | v       |           0 | 0 bytes
 information_schema | check_constraints                              | v       |           0 | 0 bytes
 information_schema | applicable_roles                               | v       |           0 | 0 bytes
 information_schema | administrable_role_authorizations              | v       |           0 | 0 bytes
 information_schema | column_column_usage                            | v       |           0 | 0 bytes
 information_schema | attributes                                     | v       |           0 | 0 bytes
 information_schema | collations                                     | v       |           0 | 0 bytes
 information_schema | character_sets                                 | v       |           0 | 0 bytes
 information_schema | check_constraint_routine_usage                 | v       |           0 | 0 bytes
 information_schema | collation_character_set_applicability          | v       |           0 | 0 bytes
 information_schema | column_privileges                              | v       |           0 | 0 bytes
 information_schema | column_domain_usage                            | v       |           0 | 0 bytes
 information_schema | column_udt_usage                               | v       |           0 | 0 bytes
 information_schema | columns                                        | v       |           0 | 0 bytes
 information_schema | constraint_column_usage                        | v       |           0 | 0 bytes
 information_schema | constraint_table_usage                         | v       |           0 | 0 bytes
 information_schema | data_type_privileges                           | v       |           0 | 0 bytes
 information_schema | table_constraints                              | v       |           0 | 0 bytes
 information_schema | role_usage_grants                              | v       |           0 | 0 bytes
 information_schema | table_privileges                               | v       |           0 | 0 bytes
 information_schema | role_table_grants                              | v       |           0 | 0 bytes
 information_schema | tables                                         | v       |           0 | 0 bytes
 information_schema | transforms                                     | v       |           0 | 0 bytes
 information_schema | user_defined_types                             | v       |           0 | 0 bytes
 information_schema | triggered_update_columns                       | v       |           0 | 0 bytes
 information_schema | triggers                                       | v       |           0 | 0 bytes
 information_schema | udt_privileges                                 | v       |           0 | 0 bytes
 information_schema | view_column_usage                              | v       |           0 | 0 bytes
 information_schema | role_udt_grants                                | v       |           0 | 0 bytes
 information_schema | usage_privileges                               | v       |           0 | 0 bytes
 information_schema | element_types                                  | v       |           0 | 0 bytes
 information_schema | view_routine_usage                             | v       |           0 | 0 bytes
 information_schema | view_table_usage                               | v       |           0 | 0 bytes
 information_schema | _pg_foreign_table_columns                      | v       |           0 | 0 bytes
 information_schema | views                                          | v       |           0 | 0 bytes
 information_schema | _pg_foreign_servers                            | v       |           0 | 0 bytes
 information_schema | foreign_data_wrapper_options                   | v       |           0 | 0 bytes
 information_schema | column_options                                 | v       |           0 | 0 bytes
 information_schema | _pg_foreign_data_wrappers                      | v       |           0 | 0 bytes
 pg_catalog         | pg_config                                      | v       |           0 | 0 bytes
 pg_catalog         | pg_shmem_allocations                           | v       |           0 | 0 bytes
 pg_catalog         | pg_shmem_allocations_numa                      | v       |           0 | 0 bytes
 information_schema | schemata                                       | v       |           0 | 0 bytes
 information_schema | domain_constraints                             | v       |           0 | 0 bytes
 information_schema | routine_column_usage                           | v       |           0 | 0 bytes
 information_schema | domain_udt_usage                               | v       |           0 | 0 bytes
 information_schema | domains                                        | v       |           0 | 0 bytes
 information_schema | enabled_roles                                  | v       |           0 | 0 bytes
 information_schema | routine_table_usage                            | v       |           0 | 0 bytes
 information_schema | routine_privileges                             | v       |           0 | 0 bytes
 information_schema | key_column_usage                               | v       |           0 | 0 bytes
 information_schema | parameters                                     | v       |           0 | 0 bytes
 information_schema | referential_constraints                        | v       |           0 | 0 bytes
 information_schema | role_routine_grants                            | v       |           0 | 0 bytes
 information_schema | role_column_grants                             | v       |           0 | 0 bytes
 pg_catalog         | pg_backend_memory_contexts                     | v       |           0 | 0 bytes
 pg_catalog         | pg_replication_origin_status                   | v       |           0 | 0 bytes
 pg_catalog         | pg_hba_file_rules                              | v       |           0 | 0 bytes
 information_schema | routine_routine_usage                          | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_sys_sequences                        | v       |           0 | 0 bytes
 pg_catalog         | pg_statio_user_sequences                       | v       |           0 | 0 bytes
 pg_catalog         | pg_aios                                        | v       |           0 | 0 bytes
 pg_catalog         | pg_file_settings                               | v       |           0 | 0 bytes
 pg_catalog         | pg_settings                                    | v       |           0 | 0 bytes
 pg_catalog         | pg_ident_file_mappings                         | v       |           0 | 0 bytes
 pg_catalog         | pg_roles                                       | v       |           0 | 0 bytes
 pg_catalog         | pg_stat_activity                               | v       |           0 | 0 bytes
 information_schema | routines                                       | v       |           0 | 0 bytes
 information_schema | routine_sequence_usage                         | v       |           0 | 0 bytes
 information_schema | sequences                                      | v       |           0 | 0 bytes
 pg_catalog         | pg_shadow                                      | v       |           0 | 0 bytes
 information_schema | foreign_data_wrappers                          | v       |           0 | 0 bytes
 information_schema | _pg_foreign_tables                             | v       |           0 | 0 bytes
 information_schema | foreign_server_options                         | v       |           0 | 0 bytes
 information_schema | foreign_servers                                | v       |           0 | 0 bytes
 information_schema | foreign_table_options                          | v       |           0 | 0 bytes
 information_schema | foreign_tables                                 | v       |           0 | 0 bytes
 information_schema | _pg_user_mappings                              | v       |           0 | 0 bytes
 information_schema | user_mapping_options                           | v       |           0 | 0 bytes
 information_schema | user_mappings                                  | v       |           0 | 0 bytes
 pg_catalog         | pg_group                                       | v       |           0 | 0 bytes
 pg_catalog         | pg_user                                        | v       |           0 | 0 bytes
 pg_catalog         | pg_policies                                    | v       |           0 | 0 bytes
 pg_catalog         | pg_rules                                       | v       |           0 | 0 bytes
 pg_catalog         | pg_views                                       | v       |           0 | 0 bytes
 pg_catalog         | pg_tables                                      | v       |           0 | 0 bytes
 pg_catalog         | pg_matviews                                    | v       |           0 | 0 bytes
 pg_catalog         | pg_indexes                                     | v       |           0 | 0 bytes
 pg_catalog         | pg_sequences                                   | v       |           0 | 0 bytes
 pg_catalog         | pg_stats                                       | v       |           0 | 0 bytes
 pg_catalog         | pg_stats_ext                                   | v       |           0 | 0 bytes
 pg_catalog         | pg_stats_ext_exprs                             | v       |           0 | 0 bytes
 pg_catalog         | pg_publication_tables                          | v       |           0 | 0 bytes
 pg_catalog         | pg_locks                                       | v       |           0 | 0 bytes
 pg_catalog         | pg_cursors                                     | v       |           0 | 0 bytes
(337 rows)


SAMPLE_OUTPUT_END */
