/*
Purpose: Show table-level grants for non-system schemas.
Area: Security and Roles
Usage: Use to audit object privileges by grantee.
*/
SELECT
    table_schema,
    table_name,
    grantee,
    privilege_type,
    is_grantable
FROM information_schema.table_privileges
WHERE table_schema !~ '^pg_'
  AND table_schema <> 'information_schema'
ORDER BY table_schema, table_name, grantee, privilege_type;




-- SAMPLE_OUTPUT_BEGIN
-- Sample output captured from database: pgbench_test
-- Capture run directory: /tmp/pgbench_full_refresh_clean_20260218_194330
--
--    table_schema   |       table_name        |       grantee       | privilege_type | is_grantable 
-- ------------------+-------------------------+---------------------+----------------+--------------
--  dba_metrics      | connection_snapshots    | saiendla            | DELETE         | YES
--  dba_metrics      | connection_snapshots    | saiendla            | INSERT         | YES
--  dba_metrics      | connection_snapshots    | saiendla            | REFERENCES     | YES
--  dba_metrics      | connection_snapshots    | saiendla            | SELECT         | YES
--  dba_metrics      | connection_snapshots    | saiendla            | TRIGGER        | YES
--  dba_metrics      | connection_snapshots    | saiendla            | TRUNCATE       | YES
--  dba_metrics      | connection_snapshots    | saiendla            | UPDATE         | YES
--  dba_metrics      | database_size_snapshots | saiendla            | DELETE         | YES
--  dba_metrics      | database_size_snapshots | saiendla            | INSERT         | YES
--  dba_metrics      | database_size_snapshots | saiendla            | REFERENCES     | YES
--  dba_metrics      | database_size_snapshots | saiendla            | SELECT         | YES
--  dba_metrics      | database_size_snapshots | saiendla            | TRIGGER        | YES
--  dba_metrics      | database_size_snapshots | saiendla            | TRUNCATE       | YES
--  dba_metrics      | database_size_snapshots | saiendla            | UPDATE         | YES
--  dba_metrics      | index_size_snapshots    | saiendla            | DELETE         | YES
--  dba_metrics      | index_size_snapshots    | saiendla            | INSERT         | YES
--  dba_metrics      | index_size_snapshots    | saiendla            | REFERENCES     | YES
--  dba_metrics      | index_size_snapshots    | saiendla            | SELECT         | YES
--  dba_metrics      | index_size_snapshots    | saiendla            | TRIGGER        | YES
--  dba_metrics      | index_size_snapshots    | saiendla            | TRUNCATE       | YES
--  dba_metrics      | index_size_snapshots    | saiendla            | UPDATE         | YES
--  dba_metrics      | table_size_snapshots    | saiendla            | DELETE         | YES
--  dba_metrics      | table_size_snapshots    | saiendla            | INSERT         | YES
--  dba_metrics      | table_size_snapshots    | saiendla            | REFERENCES     | YES
--  dba_metrics      | table_size_snapshots    | saiendla            | SELECT         | YES
--  dba_metrics      | table_size_snapshots    | saiendla            | TRIGGER        | YES
--  dba_metrics      | table_size_snapshots    | saiendla            | TRUNCATE       | YES
--  dba_metrics      | table_size_snapshots    | saiendla            | UPDATE         | YES
--  dba_metrics      | wal_snapshots           | saiendla            | DELETE         | YES
--  dba_metrics      | wal_snapshots           | saiendla            | INSERT         | YES
--  dba_metrics      | wal_snapshots           | saiendla            | REFERENCES     | YES
--  dba_metrics      | wal_snapshots           | saiendla            | SELECT         | YES
--  dba_metrics      | wal_snapshots           | saiendla            | TRIGGER        | YES
--  dba_metrics      | wal_snapshots           | saiendla            | TRUNCATE       | YES
--  dba_metrics      | wal_snapshots           | saiendla            | UPDATE         | YES
--  migration_v1_lab | child_transactions      | saiendla            | DELETE         | YES
--  migration_v1_lab | child_transactions      | saiendla            | INSERT         | YES
--  migration_v1_lab | child_transactions      | saiendla            | REFERENCES     | YES
--  migration_v1_lab | child_transactions      | saiendla            | SELECT         | YES
--  migration_v1_lab | child_transactions      | saiendla            | TRIGGER        | YES
--  migration_v1_lab | child_transactions      | saiendla            | TRUNCATE       | YES
--  migration_v1_lab | child_transactions      | saiendla            | UPDATE         | YES
--  migration_v1_lab | dml_bloat_table         | saiendla            | DELETE         | YES
--  migration_v1_lab | dml_bloat_table         | saiendla            | INSERT         | YES
--  migration_v1_lab | dml_bloat_table         | saiendla            | REFERENCES     | YES
--  migration_v1_lab | dml_bloat_table         | saiendla            | SELECT         | YES
--  migration_v1_lab | dml_bloat_table         | saiendla            | TRIGGER        | YES
--  migration_v1_lab | dml_bloat_table         | saiendla            | TRUNCATE       | YES
--  migration_v1_lab | dml_bloat_table         | saiendla            | UPDATE         | YES
--  migration_v1_lab | orders_no_pk            | saiendla            | DELETE         | YES
--  migration_v1_lab | orders_no_pk            | saiendla            | INSERT         | YES
--  migration_v1_lab | orders_no_pk            | saiendla            | REFERENCES     | YES
--  migration_v1_lab | orders_no_pk            | saiendla            | SELECT         | YES
--  migration_v1_lab | orders_no_pk            | saiendla            | TRIGGER        | YES
--  migration_v1_lab | orders_no_pk            | saiendla            | TRUNCATE       | YES
--  migration_v1_lab | orders_no_pk            | saiendla            | UPDATE         | YES
--  migration_v1_lab | parent_accounts         | saiendla            | DELETE         | YES
--  migration_v1_lab | parent_accounts         | saiendla            | INSERT         | YES
--  migration_v1_lab | parent_accounts         | saiendla            | REFERENCES     | YES
--  migration_v1_lab | parent_accounts         | saiendla            | SELECT         | YES
--  migration_v1_lab | parent_accounts         | saiendla            | TRIGGER        | YES
--  migration_v1_lab | parent_accounts         | saiendla            | TRUNCATE       | YES
--  migration_v1_lab | parent_accounts         | saiendla            | UPDATE         | YES
--  migration_v1_lab | product_catalog         | saiendla            | DELETE         | YES
--  migration_v1_lab | product_catalog         | saiendla            | INSERT         | YES
--  migration_v1_lab | product_catalog         | saiendla            | REFERENCES     | YES
--  migration_v1_lab | product_catalog         | saiendla            | SELECT         | YES
--  migration_v1_lab | product_catalog         | saiendla            | TRIGGER        | YES
--  migration_v1_lab | product_catalog         | saiendla            | TRUNCATE       | YES
--  migration_v1_lab | product_catalog         | saiendla            | UPDATE         | YES
--  migration_v1_lab | sales_orders            | saiendla            | DELETE         | YES
--  migration_v1_lab | sales_orders            | saiendla            | INSERT         | YES
--  migration_v1_lab | sales_orders            | saiendla            | REFERENCES     | YES
--  migration_v1_lab | sales_orders            | saiendla            | SELECT         | YES
--  migration_v1_lab | sales_orders            | saiendla            | TRIGGER        | YES
--  migration_v1_lab | sales_orders            | saiendla            | TRUNCATE       | YES
--  migration_v1_lab | sales_orders            | saiendla            | UPDATE         | YES
--  migration_v1_lab | stale_stats_table       | saiendla            | DELETE         | YES
--  migration_v1_lab | stale_stats_table       | saiendla            | INSERT         | YES
--  migration_v1_lab | stale_stats_table       | saiendla            | REFERENCES     | YES
--  migration_v1_lab | stale_stats_table       | saiendla            | SELECT         | YES
--  migration_v1_lab | stale_stats_table       | saiendla            | TRIGGER        | YES
--  migration_v1_lab | stale_stats_table       | saiendla            | TRUNCATE       | YES
--  migration_v1_lab | stale_stats_table       | saiendla            | UPDATE         | YES
--  migration_v2_lab | amount_mapping_risk     | saiendla            | DELETE         | YES
--  migration_v2_lab | amount_mapping_risk     | saiendla            | INSERT         | YES
--  migration_v2_lab | amount_mapping_risk     | saiendla            | REFERENCES     | YES
--  migration_v2_lab | amount_mapping_risk     | saiendla            | SELECT         | YES
--  migration_v2_lab | amount_mapping_risk     | saiendla            | TRIGGER        | YES
--  migration_v2_lab | amount_mapping_risk     | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | amount_mapping_risk     | saiendla            | UPDATE         | YES
--  migration_v2_lab | bloat_pressure_table    | saiendla            | DELETE         | YES
--  migration_v2_lab | bloat_pressure_table    | saiendla            | INSERT         | YES
--  migration_v2_lab | bloat_pressure_table    | saiendla            | REFERENCES     | YES
--  migration_v2_lab | bloat_pressure_table    | saiendla            | SELECT         | YES
--  migration_v2_lab | bloat_pressure_table    | saiendla            | TRIGGER        | YES
--  migration_v2_lab | bloat_pressure_table    | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | bloat_pressure_table    | saiendla            | UPDATE         | YES
--  migration_v2_lab | child_events            | saiendla            | DELETE         | YES
--  migration_v2_lab | child_events            | saiendla            | INSERT         | YES
--  migration_v2_lab | child_events            | saiendla            | REFERENCES     | YES
--  migration_v2_lab | child_events            | saiendla            | SELECT         | YES
--  migration_v2_lab | child_events            | saiendla            | TRIGGER        | YES
--  migration_v2_lab | child_events            | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | child_events            | saiendla            | UPDATE         | YES
--  migration_v2_lab | customer_contact_compat | saiendla            | DELETE         | YES
--  migration_v2_lab | customer_contact_compat | saiendla            | INSERT         | YES
--  migration_v2_lab | customer_contact_compat | saiendla            | REFERENCES     | YES
--  migration_v2_lab | customer_contact_compat | saiendla            | SELECT         | YES
--  migration_v2_lab | customer_contact_compat | saiendla            | TRIGGER        | YES
--  migration_v2_lab | customer_contact_compat | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | customer_contact_compat | saiendla            | UPDATE         | YES
--  migration_v2_lab | customer_staging_no_pk  | saiendla            | DELETE         | YES
--  migration_v2_lab | customer_staging_no_pk  | saiendla            | INSERT         | YES
--  migration_v2_lab | customer_staging_no_pk  | saiendla            | REFERENCES     | YES
--  migration_v2_lab | customer_staging_no_pk  | saiendla            | SELECT         | YES
--  migration_v2_lab | customer_staging_no_pk  | saiendla            | TRIGGER        | YES
--  migration_v2_lab | customer_staging_no_pk  | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | customer_staging_no_pk  | saiendla            | UPDATE         | YES
--  migration_v2_lab | issue_manifest          | saiendla            | DELETE         | YES
--  migration_v2_lab | issue_manifest          | saiendla            | INSERT         | YES
--  migration_v2_lab | issue_manifest          | saiendla            | REFERENCES     | YES
--  migration_v2_lab | issue_manifest          | saiendla            | SELECT         | YES
--  migration_v2_lab | issue_manifest          | saiendla            | TRIGGER        | YES
--  migration_v2_lab | issue_manifest          | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | issue_manifest          | saiendla            | UPDATE         | YES
--  migration_v2_lab | order_fact              | migration_v2_reader | SELECT         | NO
--  migration_v2_lab | order_fact              | saiendla            | DELETE         | YES
--  migration_v2_lab | order_fact              | saiendla            | INSERT         | YES
--  migration_v2_lab | order_fact              | saiendla            | REFERENCES     | YES
--  migration_v2_lab | order_fact              | saiendla            | SELECT         | YES
--  migration_v2_lab | order_fact              | saiendla            | TRIGGER        | YES
--  migration_v2_lab | order_fact              | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | order_fact              | saiendla            | UPDATE         | YES
--  migration_v2_lab | parent_accounts         | saiendla            | DELETE         | YES
--  migration_v2_lab | parent_accounts         | saiendla            | INSERT         | YES
--  migration_v2_lab | parent_accounts         | saiendla            | REFERENCES     | YES
--  migration_v2_lab | parent_accounts         | saiendla            | SELECT         | YES
--  migration_v2_lab | parent_accounts         | saiendla            | TRIGGER        | YES
--  migration_v2_lab | parent_accounts         | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | parent_accounts         | saiendla            | UPDATE         | YES
--  migration_v2_lab | partitioned_events      | saiendla            | DELETE         | YES
--  migration_v2_lab | partitioned_events      | saiendla            | INSERT         | YES
--  migration_v2_lab | partitioned_events      | saiendla            | REFERENCES     | YES
--  migration_v2_lab | partitioned_events      | saiendla            | SELECT         | YES
--  migration_v2_lab | partitioned_events      | saiendla            | TRIGGER        | YES
--  migration_v2_lab | partitioned_events      | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | partitioned_events      | saiendla            | UPDATE         | YES
--  migration_v2_lab | partitioned_events_2025 | saiendla            | DELETE         | YES
--  migration_v2_lab | partitioned_events_2025 | saiendla            | INSERT         | YES
--  migration_v2_lab | partitioned_events_2025 | saiendla            | REFERENCES     | YES
--  migration_v2_lab | partitioned_events_2025 | saiendla            | SELECT         | YES
--  migration_v2_lab | partitioned_events_2025 | saiendla            | TRIGGER        | YES
--  migration_v2_lab | partitioned_events_2025 | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | partitioned_events_2025 | saiendla            | UPDATE         | YES
--  migration_v2_lab | partitioned_events_2026 | saiendla            | DELETE         | YES
--  migration_v2_lab | partitioned_events_2026 | saiendla            | INSERT         | YES
--  migration_v2_lab | partitioned_events_2026 | saiendla            | REFERENCES     | YES
--  migration_v2_lab | partitioned_events_2026 | saiendla            | SELECT         | YES
--  migration_v2_lab | partitioned_events_2026 | saiendla            | TRIGGER        | YES
--  migration_v2_lab | partitioned_events_2026 | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | partitioned_events_2026 | saiendla            | UPDATE         | YES
--  migration_v2_lab | quoted_orders           | saiendla            | DELETE         | YES
--  migration_v2_lab | quoted_orders           | saiendla            | INSERT         | YES
--  migration_v2_lab | quoted_orders           | saiendla            | REFERENCES     | YES
--  migration_v2_lab | quoted_orders           | saiendla            | SELECT         | YES
--  migration_v2_lab | quoted_orders           | saiendla            | TRIGGER        | YES
--  migration_v2_lab | quoted_orders           | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | quoted_orders           | saiendla            | UPDATE         | YES
--  migration_v2_lab | sales_catalog           | saiendla            | DELETE         | YES
--  migration_v2_lab | sales_catalog           | saiendla            | INSERT         | YES
--  migration_v2_lab | sales_catalog           | saiendla            | REFERENCES     | YES
--  migration_v2_lab | sales_catalog           | saiendla            | SELECT         | YES
--  migration_v2_lab | sales_catalog           | saiendla            | TRIGGER        | YES
--  migration_v2_lab | sales_catalog           | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | sales_catalog           | saiendla            | UPDATE         | YES
--  migration_v2_lab | stale_stats_table       | saiendla            | DELETE         | YES
--  migration_v2_lab | stale_stats_table       | saiendla            | INSERT         | YES
--  migration_v2_lab | stale_stats_table       | saiendla            | REFERENCES     | YES
--  migration_v2_lab | stale_stats_table       | saiendla            | SELECT         | YES
--  migration_v2_lab | stale_stats_table       | saiendla            | TRIGGER        | YES
--  migration_v2_lab | stale_stats_table       | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | stale_stats_table       | saiendla            | UPDATE         | YES
--  migration_v2_lab | trigger_audit_demo      | saiendla            | DELETE         | YES
--  migration_v2_lab | trigger_audit_demo      | saiendla            | INSERT         | YES
--  migration_v2_lab | trigger_audit_demo      | saiendla            | REFERENCES     | YES
--  migration_v2_lab | trigger_audit_demo      | saiendla            | SELECT         | YES
--  migration_v2_lab | trigger_audit_demo      | saiendla            | TRIGGER        | YES
--  migration_v2_lab | trigger_audit_demo      | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | trigger_audit_demo      | saiendla            | UPDATE         | YES
--  migration_v2_lab | vw_high_value_orders    | migration_v2_reader | SELECT         | NO
--  migration_v2_lab | vw_high_value_orders    | saiendla            | DELETE         | YES
--  migration_v2_lab | vw_high_value_orders    | saiendla            | INSERT         | YES
--  migration_v2_lab | vw_high_value_orders    | saiendla            | REFERENCES     | YES
--  migration_v2_lab | vw_high_value_orders    | saiendla            | SELECT         | YES
--  migration_v2_lab | vw_high_value_orders    | saiendla            | TRIGGER        | YES
--  migration_v2_lab | vw_high_value_orders    | saiendla            | TRUNCATE       | YES
--  migration_v2_lab | vw_high_value_orders    | saiendla            | UPDATE         | YES
--  public           | pg_stat_statements      | PUBLIC              | SELECT         | NO
--  public           | pg_stat_statements      | saiendla            | DELETE         | YES
--  public           | pg_stat_statements      | saiendla            | INSERT         | YES
--  public           | pg_stat_statements      | saiendla            | REFERENCES     | YES
--  public           | pg_stat_statements      | saiendla            | SELECT         | YES
--  public           | pg_stat_statements      | saiendla            | TRIGGER        | YES
--  public           | pg_stat_statements      | saiendla            | TRUNCATE       | YES
--  public           | pg_stat_statements      | saiendla            | UPDATE         | YES
--  public           | pg_stat_statements_info | PUBLIC              | SELECT         | NO
--  public           | pg_stat_statements_info | saiendla            | DELETE         | YES
--  public           | pg_stat_statements_info | saiendla            | INSERT         | YES
--  public           | pg_stat_statements_info | saiendla            | REFERENCES     | YES
--  public           | pg_stat_statements_info | saiendla            | SELECT         | YES
--  public           | pg_stat_statements_info | saiendla            | TRIGGER        | YES
--  public           | pg_stat_statements_info | saiendla            | TRUNCATE       | YES
--  public           | pg_stat_statements_info | saiendla            | UPDATE         | YES
--  public           | pgbench_accounts        | saiendla            | DELETE         | YES
--  public           | pgbench_accounts        | saiendla            | INSERT         | YES
--  public           | pgbench_accounts        | saiendla            | REFERENCES     | YES
--  public           | pgbench_accounts        | saiendla            | SELECT         | YES
--  public           | pgbench_accounts        | saiendla            | TRIGGER        | YES
--  public           | pgbench_accounts        | saiendla            | TRUNCATE       | YES
--  public           | pgbench_accounts        | saiendla            | UPDATE         | YES
--  public           | pgbench_branches        | saiendla            | DELETE         | YES
--  public           | pgbench_branches        | saiendla            | INSERT         | YES
--  public           | pgbench_branches        | saiendla            | REFERENCES     | YES
--  public           | pgbench_branches        | saiendla            | SELECT         | YES
--  public           | pgbench_branches        | saiendla            | TRIGGER        | YES
--  public           | pgbench_branches        | saiendla            | TRUNCATE       | YES
--  public           | pgbench_branches        | saiendla            | UPDATE         | YES
--  public           | pgbench_history         | saiendla            | DELETE         | YES
--  public           | pgbench_history         | saiendla            | INSERT         | YES
--  public           | pgbench_history         | saiendla            | REFERENCES     | YES
--  public           | pgbench_history         | saiendla            | SELECT         | YES
--  public           | pgbench_history         | saiendla            | TRIGGER        | YES
--  public           | pgbench_history         | saiendla            | TRUNCATE       | YES
--  public           | pgbench_history         | saiendla            | UPDATE         | YES
--  public           | pgbench_tellers         | saiendla            | DELETE         | YES
--  public           | pgbench_tellers         | saiendla            | INSERT         | YES
--  public           | pgbench_tellers         | saiendla            | REFERENCES     | YES
--  public           | pgbench_tellers         | saiendla            | SELECT         | YES
--  public           | pgbench_tellers         | saiendla            | TRIGGER        | YES
--  public           | pgbench_tellers         | saiendla            | TRUNCATE       | YES
--  public           | pgbench_tellers         | saiendla            | UPDATE         | YES
-- (242 rows)
-- 
-- SAMPLE_OUTPUT_END
