/*
Oracle DBA Script: Partition Lab Generate 5gb Timeseries
Purpose: Provide Oracle DBA diagnostics for partition lab generate 5gb timeseries.
Area: Partitioning
Usage: Run with SQL*Plus or SQLcl as a user with SELECT_CATALOG_ROLE, DBA, or explicit access to the referenced DBA_/GV$/V$ views.
Notes: Review findings before taking action. Some performance history views require the Oracle Diagnostics Pack license.
*/
SET LINESIZE 220
SET PAGESIZE 200
SET TRIMSPOOL ON
SET TAB OFF
COLUMN owner FORMAT A28
COLUMN object_name FORMAT A38
COLUMN segment_name FORMAT A38
COLUMN table_name FORMAT A38
COLUMN index_name FORMAT A38
COLUMN sql_id FORMAT A14
COLUMN event FORMAT A48
COLUMN parameter_name FORMAT A45
COLUMN value FORMAT A45

PROMPT Partition Lab Generate 5gb Timeseries

PROMPT Review and edit this lab DDL before running in a non-production schema.
CREATE TABLE oracle_partition_lab_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_ts TIMESTAMP NOT NULL,
    customer_id NUMBER NOT NULL,
    amount NUMBER(12,2),
    CONSTRAINT oracle_partition_lab_orders_pk PRIMARY KEY (order_id)
)
PARTITION BY RANGE (order_ts)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) (
    PARTITION p_seed VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00')
);
